.PHONY: generate-templates
generate-templates:
	cp -f $(CURDIR)/../../tools/utils/setup_templates/generate-templates/trackers/ttm-campaign.xml \
		resources/Tracker_campaign.xml
	cp -f $(CURDIR)/../../tools/utils/setup_templates/generate-templates/trackers/ttm-def.xml \
		resources/Tracker_test_def.xml
	cp -f $(CURDIR)/../../tools/utils/setup_templates/generate-templates/trackers/ttm-exec.xml \
		resources/Tracker_test_exec.xml
