<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload990f9f4d054ea9ab5858accaa8297f1d($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'arc2' => '/arc/ARC2.php',
            'arc2_atomparser' => '/arc/parsers/ARC2_AtomParser.php',
            'arc2_cbjsonparser' => '/arc/parsers/ARC2_CBJSONParser.php',
            'arc2_class' => '/arc/ARC2_Class.php',
            'arc2_dcextractor' => '/arc/extractors/ARC2_DcExtractor.php',
            'arc2_erdfextractor' => '/arc/extractors/ARC2_ErdfExtractor.php',
            'arc2_jsonparser' => '/arc/parsers/ARC2_JSONParser.php',
            'arc2_legacyhtmlserializer' => '/arc/serializers/ARC2_LegacyHTMLSerializer.php',
            'arc2_legacyjsonserializer' => '/arc/serializers/ARC2_LegacyJSONSerializer.php',
            'arc2_legacyxmlparser' => '/arc/parsers/ARC2_LegacyXMLParser.php',
            'arc2_legacyxmlserializer' => '/arc/serializers/ARC2_LegacyXMLSerializer.php',
            'arc2_microformatsextractor' => '/arc/extractors/ARC2_MicroformatsExtractor.php',
            'arc2_micrordfserializer' => '/arc/serializers/ARC2_MicroRDFSerializer.php',
            'arc2_ntriplesserializer' => '/arc/serializers/ARC2_NTriplesSerializer.php',
            'arc2_openidextractor' => '/arc/extractors/ARC2_OpenidExtractor.php',
            'arc2_poshrdfextractor' => '/arc/extractors/ARC2_PoshRdfExtractor.php',
            'arc2_poshrdfserializer' => '/arc/serializers/ARC2_POSHRDFSerializer.php',
            'arc2_rdfaextractor' => '/arc/extractors/ARC2_RdfaExtractor.php',
            'arc2_rdfextractor' => '/arc/extractors/ARC2_RDFExtractor.php',
            'arc2_rdfjsonserializer' => '/arc/serializers/ARC2_RDFJSONSerializer.php',
            'arc2_rdfparser' => '/arc/parsers/ARC2_RDFParser.php',
            'arc2_rdfserializer' => '/arc/serializers/ARC2_RDFSerializer.php',
            'arc2_rdfxmlparser' => '/arc/parsers/ARC2_RDFXMLParser.php',
            'arc2_rdfxmlserializer' => '/arc/serializers/ARC2_RDFXMLSerializer.php',
            'arc2_reader' => '/arc/ARC2_Reader.php',
            'arc2_remotestore' => '/arc/store/ARC2_RemoteStore.php',
            'arc2_resource' => '/arc/ARC2_Resource.php',
            'arc2_rss10serializer' => '/arc/serializers/ARC2_RSS10Serializer.php',
            'arc2_rssparser' => '/arc/parsers/ARC2_RSSParser.php',
            'arc2_semhtmlparser' => '/arc/parsers/ARC2_SemHTMLParser.php',
            'arc2_sgajsonparser' => '/arc/parsers/ARC2_SGAJSONParser.php',
            'arc2_sparqlparser' => '/arc/parsers/ARC2_SPARQLParser.php',
            'arc2_sparqlplusparser' => '/arc/parsers/ARC2_SPARQLPlusParser.php',
            'arc2_sparqlscriptparser' => '/arc/sparqlscript/ARC2_SPARQLScriptParser.php',
            'arc2_sparqlscriptprocessor' => '/arc/sparqlscript/ARC2_SPARQLScriptProcessor.php',
            'arc2_sparqlxmlresultparser' => '/arc/parsers/ARC2_SPARQLXMLResultParser.php',
            'arc2_spogparser' => '/arc/parsers/ARC2_SPOGParser.php',
            'arc2_store' => '/arc/store/ARC2_Store.php',
            'arc2_storeaskqueryhandler' => '/arc/store/ARC2_StoreAskQueryHandler.php',
            'arc2_storeatomloader' => '/arc/store/ARC2_StoreAtomLoader.php',
            'arc2_storecbjsonloader' => '/arc/store/ARC2_StoreCBJSONLoader.php',
            'arc2_storeconstructqueryhandler' => '/arc/store/ARC2_StoreConstructQueryHandler.php',
            'arc2_storedeletequeryhandler' => '/arc/store/ARC2_StoreDeleteQueryHandler.php',
            'arc2_storedescribequeryhandler' => '/arc/store/ARC2_StoreDescribeQueryHandler.php',
            'arc2_storedumper' => '/arc/store/ARC2_StoreDumper.php',
            'arc2_storedumpqueryhandler' => '/arc/store/ARC2_StoreDumpQueryHandler.php',
            'arc2_storeendpoint' => '/arc/store/ARC2_StoreEndpoint.php',
            'arc2_storehelper' => '/arc/store/ARC2_StoreHelper.php',
            'arc2_storeinsertqueryhandler' => '/arc/store/ARC2_StoreInsertQueryHandler.php',
            'arc2_storeloadqueryhandler' => '/arc/store/ARC2_StoreLoadQueryHandler.php',
            'arc2_storequeryhandler' => '/arc/store/ARC2_StoreQueryHandler.php',
            'arc2_storerdfxmlloader' => '/arc/store/ARC2_StoreRDFXMLLoader.php',
            'arc2_storerssloader' => '/arc/store/ARC2_StoreRSSLoader.php',
            'arc2_storeselectqueryhandler' => '/arc/store/ARC2_StoreSelectQueryHandler.php',
            'arc2_storesemhtmlloader' => '/arc/store/ARC2_StoreSemHTMLLoader.php',
            'arc2_storesgajsonloader' => '/arc/store/ARC2_StoreSGAJSONLoader.php',
            'arc2_storespogloader' => '/arc/store/ARC2_StoreSPOGLoader.php',
            'arc2_storetablemanager' => '/arc/store/ARC2_StoreTableManager.php',
            'arc2_storeturtleloader' => '/arc/store/ARC2_StoreTurtleLoader.php',
            'arc2_turtleparser' => '/arc/parsers/ARC2_TurtleParser.php',
            'arc2_turtleserializer' => '/arc/serializers/ARC2_TurtleSerializer.php',
            'arc2_twitterprofilepicextractor' => '/arc/extractors/ARC2_TwitterProfilePicExtractor.php',
            'fusionforge' => '/fusionforge/FusionForge.php',
            'fusionforge_compatplugin' => '/fusionforge_compatPlugin.class.php',
            'pfo_rbacengine' => '/fusionforge/PFO-RBAC.interface.php',
            'pfo_role' => '/fusionforge/PFO-RBAC.interface.php',
            'pfo_roleanonymous' => '/fusionforge/PFO-RBAC.interface.php',
            'pfo_roleexplicit' => '/fusionforge/PFO-RBAC.interface.php',
            'pfo_roleloggedin' => '/fusionforge/PFO-RBAC.interface.php',
            'pfo_roleunion' => '/fusionforge/PFO-RBAC.interface.php',
            'pluginspecificrolesetting' => '/include/plugins_utils.php',
            'rbacengine' => '/fusionforge/RBAC.php',
            'role' => '/fusionforge/RBAC.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload990f9f4d054ea9ab5858accaa8297f1d');
// @codeCoverageIgnoreEnd