<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload05f5f6356f162273d6e2d918b3f49691($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'templateplugin' => '/templatePlugin.php',
            'tuleap\\template\\plugin\\plugindescriptor' => '/Template/Plugin/PluginDescriptor.php',
            'tuleap\\template\\plugin\\plugininfo' => '/Template/Plugin/PluginInfo.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload05f5f6356f162273d6e2d918b3f49691');
// @codeCoverageIgnoreEnd
