<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload48d302ec5e8adc15aa22ef1acb6c7bd9($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'templateplugin' => '/templatePlugin.class.php',
            'templateplugindescriptor' => '/TemplatePluginDescriptor.class.php',
            'templateplugininfo' => '/TemplatePluginInfo.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload48d302ec5e8adc15aa22ef1acb6c7bd9');
// @codeCoverageIgnoreEnd