<?
/**
  * Copyright (c) Enalean, 2013. All rights reserved
  *
  * This file is a part of Tuleap.
  *
  * Tuleap is free software; you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation; either version 2 of the License, or
  * (at your option) any later version.
  *
  * Tuleap is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with Tuleap. If not, see <http://www.gnu.org/licenses/
  */

/* @var $this->single_step_project OneStepProjectCreationForm */
require_once 'common/project/OneStepProjectCreationForm.class.php';
?>
<div class="one_step_project container">
    <form class="one_step_project" action="<?= $this->single_step_project->getFormSubmissionPath(); ?>" method="post">
        <input type="hidden" name="onestep" value="true" />
        <p>
            <h1 class="one_step_project">Project Creation Request</h1>
        </p>

        <p class="one_step_project">Creating a new project on tuleap only takes a few steps.
            <br />
            <br />
            <span class="label label-warning">Warning</span> Before being able to do anything with your project, a system administrator must approve the project.
        </p>

        <legend>Describe your project</legend>


        <table>
            <div class="control-group">
                <label class="control-label">Full name</label>
                <div class="controls">
                    <input size="40"
                           type="text"
                           name="<?= OneStepProjectCreationPresenter::FULL_NAME ?>"
                           value="<?= $this->single_step_project->getFullName(); ?>" />
                    <span class="help-block">between 3 and 40 characters</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Short name</label>
                <div class="controls">
                    <input type="text"
                           maxlength="30"
                           size="15"
                           name="<?= OneStepProjectCreationPresenter::UNIX_NAME ?>"
                           value="<?= $this->single_step_project->getUnixName(); ?>" />
                    <span class="help-block">between 3 and 30 characters length, with only characters, numbers and dashes. NO SPACES ALLOWED.<br />
                    <span class="label label-info">Info</span> The short name is a technical name used in various URLs (project URL and source code repositories) and other references.
                    </span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Short description</label>
                <div class="controls">
                    <textarea
                        name="<?= OneStepProjectCreationPresenter::SHORT_DESCRIPTION ?>"
                        wrap="virtual"
                        cols="40"
                        rows="3"><?= $this->single_step_project->getShortDescription(); ?></textarea>
                        <span class="help-block">What is the purpose of your project?</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Project Privacy</label>
                <div class="controls">
                    <input type="radio"
                           name="<?= OneStepProjectCreationPresenter::IS_PUBLIC ?>"
                           value="1"
                           <?= ($this->single_step_project->isPublic()) ? 'checked="checked"' : '' ?>
                        />
                    Public
                    <br>
                    <input type="radio"
                           name="<?= OneStepProjectCreationPresenter::IS_PUBLIC ?>"
                           value="0"
                           <?= (! $this->single_step_project->isPublic()) ? 'checked="checked"' : '' ?>
                        />
                    Private (limit access only to the project members)
                </div>
            </div>
        </table>

        <legend>Choose an appropriate template for your project</legend>

        <p>
            A project template is a pre-configured workspace: activated tools (trackers, version control system, communication tools...)
            tools customisation and configuration (workflow, documentation structure...), user groups, permissions, etc.
            <br>
            <br>
            The project template you will select provides some services. Add those you need and/ or desactivate those you will not use.
            <br>
            <br>
            You can always modify your project workspace after your project has been approved.
        </p>
        <div class="control-group">
            <div class="controls">
                <h5 class="one_step_project">Default templates</h5>
                <table class="table table-bordered table-striped">
                    <tbody>
                        <?php
                        $default_templates = $this->single_step_project->getDefaultTemplates();
                        foreach ($default_templates as $template) :
                            /* @var $template Template */
                        ?>
                            <tr>
                                <td>
                                    <input type="radio"
                                           name="<?= OneStepProjectCreationPresenter::TEMPLATE_ID ?>"
                                           value="<?= $template->getUserGroupId(); ?>"
                                           <?= ($this->single_step_project->getTemplateId() == $template->getUserGroupId()) ? 'checked="checked"' : ''; ?>
                                        />


                                    <b>
                                        <?= $template->getPurifiedUserGroupName(); ?>
                                    </b>
                                    (<?= $template->getFormattedDateRegistered($this->single_step_project->getDateFormat()); ?>)

                                    <i>
                                        <?= $template->getPurifiedShortDescription(); ?>
                                    </i>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                </td>
                                <td>
                                   <i>
                                        <?= $GLOBALS['Language']->getText('new_index','contact')  ?>:
                                        <?php
                                        foreach ($template->getAdminUserNames() as $user_name) :
                                        ?>
                                            <a href="/users/<?= $user_name ?>/">
                                                <?= $user_name ?>
                                            </a>
                                        <?php
                                        endforeach;
                                        ?>
                                    </i>
                                    <br />
                                    <br />
                                    <p>
                                        <i>Services used:</i>
                                        <?= implode($template->getServicesUsed(), ', ');?>
                                    </p>
                                </td>
                            </tr>
                        <?php
                        endforeach;
                        ?>
                    </tbody>
                </table>
                <br />
                <br />
                <h5 class="one_step_project">Projects of which you are administrator</h5>
                <table class="table table-bordered table-striped">
                    <tbody>
                        <?php
                        $user_templates = $this->single_step_project->getUserTemplates();
                        foreach ($user_templates as $template) :
                            /* @var $template Template */
                        ?>
                            <tr>
                                <td>
                                    <input type="radio"
                                           name="<?= OneStepProjectCreationPresenter::TEMPLATE_ID ?>"
                                           value="<?= $template->getUserGroupId(); ?>"
                                           <?= ($this->single_step_project->getTemplateId() == $template->getUserGroupId()) ? 'checked="checked"' : ''; ?>
                                        />
                                </td>
                                <td>
                                    <b>
                                        <?= $template->getPurifiedUserGroupName(); ?>
                                    </b>
                                    (<?= $template->getFormattedDateRegistered($this->single_step_project->getDateFormat()); ?>)
                                </td>
                                <td rowspan="2" align="left" valign="top">
                                    <i>
                                        <?= $template->getPurifiedShortDescription(); ?>
                                    </i>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                </td>
                                <td>
                                    <i>
                                        <?= $GLOBALS['Language']->getText('new_index','contact')  ?>:
                                        <?php
                                        foreach ($template->getAdminUserNames() as $user_name) :
                                        ?>
                                            <a href="/users/<?= $user_name ?>/">
                                                <?= $user_name ?>
                                            </a>
                                        <?php
                                        endforeach;
                                        ?>
                                    </i>
                                    <br />
                                    <br />
                                    <p>
                                        <i>Services used:</i>
                                        <?= implode($template->getServicesUsed(), ', ');?>
                                    </p>
                                </td>
                            </tr>
                        <?php
                        endforeach;
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
        <legend>Choose the license for your project</legend>

        <p>
            Choose the correct one because you cannot modify your project license after your project has been approved.
        </p>
        <select name="<?= OneStepProjectCreationPresenter::LICENSE_TYPE ?>">';
            <?php
            foreach ($this->available_licenses as $license_type => $license_description) :
            ?>
                <option value="<?= $license_type ?>"
                        <?= ($this->single_step_project->getLicenseType() == $license_type) ? 'selected="selected"' : ''; ?>
                        >
                    <?= $license_description ?>
                </option>
            <?php
            endforeach;
            ?>
        </select>
        <br/>
        <h3>Custom License (other)</h3>
        <textarea name="<?= OneStepProjectCreationPresenter::CUSTOM_LICENSE ?>"
                  wrap=virtual
                  cols=60
                  rows=10><?= $this->single_step_project->getCustomLicense(); ?></textarea>
        <legend>That's it !</legend>

        <p>
            You are about to request the actual project creation.
            You will receive a notification when the system administrator has validated it.
            Then, you will be able to access your new project workspace. Enjoy!
        </p>
        <input type="submit" value="submit project" name="create_project"/>
    </form>
</div>
