<?
/**
  * Copyright (c) Enalean, 2013. All rights reserved
  *
  * This file is a part of Tuleap.
  *
  * Tuleap is free software; you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation; either version 2 of the License, or
  * (at your option) any later version.
  *
  * Tuleap is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with Tuleap. If not, see <http://www.gnu.org/licenses/
  */

/* @var $this RegisterProjectOneStep */
?>
<form action="" method="get">
    <input type="hidden" name="onestep" value="true" />
    <p>
        <h1>Project Creation Request</h1>
    </p>

    <p>Creating a new project on tuleap only takes a few steps. 
        <br />
        <br />
        <span>Warning:</span> Before being able to do anything with your project, a system administrator must approve the project.
    </p>

    <h2>Describe your project</h2>
    <hr/>

    <table>
        <tr>
            <td>Full name</td>
            <td>
                <input size="40" 
                       type="text" 
                       name="form_full_name" 
                       value="<?= $this->getFullName(); ?>" />
                <br>
                between 3 and 40 characters
            </td>
        </tr>
        <tr>
            <td>Short name</td>
            <td>
                <input type="text" 
                       maxlength="30" 
                       size="15" 
                       name="form_unix_name" 
                       value="<?= $this->getUnixName(); ?>" />
                <br>
                between 3 and 30 characters length, with only characters, numbers and dashes. NO SPACES ALLOWED.
                <br>
                <span>Info</span> The short name is a technical name used in various URLs (project URL and source code repositories) and other references.
            </td>
        </tr>
        <tr>
            <td>Short description</td>
            <td>
                <textarea 
                    name="form_short_description" 
                    wrap="virtual" 
                    cols="70" 
                    rows="3">
                    <?= $this->getShortDescription(); ?>
                </textarea>
            </td>
        </tr>
        <tr>
            <td>Project Privacy</td>
            <td>
                <input type="radio" 
                       name="is_public" 
                       value="1"
                       <?= ($this->isPublic()) ? 'checked="checked"' : '' ?>
                    /> 
                Public
                <br>
                <input type="radio" 
                       name="is_public" 
                       value="0"
                       <?= (! $this->isPublic()) ? 'checked="checked"' : '' ?>
                    /> 
                Private (limit access only to the project members)
            </td>
        </tr>
    </table>

    <h2>Choose an appropriate template for your project.</h2>
    <hr/>
    <p>
        A project template is a pre-configured workspace: activated tools (trackers, version control system, communication tools...) 
        tools customisation and configuration (workflow, documentation structure...), user groups, permissions, etc.
        <br>
        <br>
        The project template you will select provides some services. Add those you need and/ or desactivate those you will not use.
        <br>
        <br>
        You can always modify your project workspace after your project has been approved.
    </p>
    <table>
        <?php 
        $default_templates = $this->getDefaultTemplates();
        foreach ($default_templates as $template) :
            /* @var $template Template */
        ?>
            <tr>
                <td>
                    <input type="radio" 
                           name="built_from_template" 
                           value="<?= $template->getUserGroupId(); ?>" 
                           <?= ($this->getTemplateId() == $template->getUserGroupId()) ? 'checked="checked"' : ''; ?>
                        />
                </td>
                <td>
                    <b>
                        <?= $template->getPurifiedUserGroupName(); ?>
                    </b> 
                    (<?= $template->getFormattedDateRegistered($this->getDateFormat()); ?>)
                </td>
                <td rowspan="2" align="left" valign="top">
                    <i>
                        <?= $template->getPurifiedShortDescription(); ?>
                    </i>
                </td>
            </tr>
            <tr>
                <td> 
                </td>
                <td>
                   <i>
                        <?= $GLOBALS['Language']->getText('new_index','contact')  ?>:
                        <?php
                        foreach ($template->getAdminUserNames() as $user_name) :
                        ?>
                            <a href="/users/<?= $user_name ?>/">  
                                <?= $user_name ?>
                            </a>
                        <?php 
                        endforeach;
                        ?>
                    </i>
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    <hr>
                </td>
            </tr>
        <?php 
        endforeach;
        ?>
    </table>
    <br />
    <table>
        <?php 
        $user_templates = $this->getUserTemplates();
        foreach ($user_templates as $template) :
            /* @var $template Template */
        ?>
            <tr>
                <td>
                    <input type="radio" 
                           name="built_from_template" 
                           value="<?= $template->getUserGroupId(); ?>" 
                           <?= ($this->getTemplateId() == $template->getUserGroupId()) ? 'checked="checked"' : ''; ?>
                        />
                </td>
                <td>
                    <b>
                        <?= $template->getPurifiedUserGroupName(); ?>
                    </b> 
                    (<?= $template->getFormattedDateRegistered($this->getDateFormat()); ?>)
                </td>
                <td rowspan="2" align="left" valign="top">
                    <i>
                        <?= $template->getPurifiedShortDescription(); ?>
                    </i>
                </td>
            </tr>
            <tr>
                <td>
                </td>
                <td>
                    <i>
                        <?= $GLOBALS['Language']->getText('new_index','contact')  ?>:
                        <?php
                        foreach ($template->getAdminUserNames() as $user_name) :
                        ?>
                            <a href="/users/<?= $user_name ?>/">  
                                <?= $user_name ?>
                            </a>
                        <?php 
                        endforeach;
                        ?>
                    </i>
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    <hr>
                </td>
            </tr>
        <?php 
        endforeach;
        ?>  
    </table>
    <h2>That's it!</h2>
    <hr/>
    <p>
        You are about to request the actual project creation. 
        You will receive a notification when the system administrator has validated it.
        Then, you will be able to access your new project workspace. Enjoy!
    </p>
    <input type="submit" value="submit project"/>
</form>





