#!/bin/bash
# stylelint pre-commit hook for git
readonly TMP_STAGING_DIR=$(mktemp -d)

cleanup_temporary_directory() {
    rm -rf "${TMP_STAGING_DIR}"
}
trap cleanup_temporary_directory EXIT

get_list_of_files() {
    git diff --cached --name-only --diff-filter=ACMRTUXB | grep \.scss$
}

get_reference_source_file() {
    local file=$1
    git diff-index --cached HEAD ${file} | cut -d ' ' -f4
}

copy_staged_file_to_temporary_directory() {
    local file=$1
    local reference=$2
    mkdir -p "$TMP_STAGING_DIR/$(dirname ${file})"
    git cat-file blob ${reference} > "${TMP_STAGING_DIR}/${file}"
    echo "${TMP_STAGING_DIR}/${file}"
}

get_list_of_mandatory_scss_files() {
    local files=$1
    local file

    for file in ${files}
    do
        local reference_file=$(get_reference_source_file "${file}")
        copy_staged_file_to_temporary_directory ${file} ${reference_file}
    done
}

main() {

    local files_list
    files_list=$(get_list_of_files)
    local files_scss_mandatory
    files_scss_mandatory=$(get_list_of_mandatory_scss_files "${files_list}")
    if [[ -n ${files_scss_mandatory} ]]
    then
        local stylelint_output
        stylelint_output=$(npm run stylelint --silent -- ${files_scss_mandatory})
        local status=$?
        if [ ${status} -ne 0 ]
        then
            echo "$stylelint_output" | less
            local formatted_files=$(tr '\n' ' ' <<< $files_list)
            local error_message="
You can run the following command to let stylelint fix a part of the errors for you:

npm run stylelint --silent -- --fix $formatted_files

"
            printf "$error_message"
        fi

        cleanup_temporary_directory
        exit ${status}
    fi
}
main
