#!/bin/sh
#
# Taken from pre-commit.sample delivered by default in .git folder

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against -- ':!*/__snapshots__/*.snap'
