#!/bin/bash
# stylelint pre-commit hook for git
get_list_of_files() {
    git diff --cached --name-only --diff-filter=ACMRTUXB | grep \.scss$
}

main() {
    local files_list
    files_list=$(get_list_of_files)
    if [[ -n ${files_list} ]]
    then
        local stylelint_output
        stylelint_output=$(npm run stylelint --silent -- ${files_list})
        local status=$?
        if [ ${status} -ne 0 ]
        then
            echo "$stylelint_output" | less
            local formatted_files=$(tr '\n' ' ' <<< $files_list)
            local error_message="
You can run the following command to let stylelint fix a part of the errors for you:

npm run stylelint --silent -- --fix $formatted_files

"
            printf "$error_message"
        fi

        exit ${status}
    fi
}
main
