#!/usr/bin/env bash
# eslint pre-commit hook for git
get_list_of_files() {
    git diff --cached --name-only --diff-filter=ACMRTUXB | grep -E '\.(js|ts|vue)$'
}

main() {
    local files_list
    files_list=$(get_list_of_files)
    if [[ -n ${files_list} ]]
    then
        local eslint_output
        eslint_output=$(pnpm --silent run eslint ${files_list})
        local status=$?
        if [ ${status} -ne 0 ]
        then
            echo "$eslint_output" | less
            local formatted_files=$(tr '\n' ' ' <<< $files_list)
            local error_message="
You can run the following command to let ESLint fix a part of the errors for you:

pnpm --silent run eslint --fix $formatted_files

"
            printf "$error_message"
        fi

        exit ${status}
    fi
}
main
