#!/usr/bin/env bash
# pre-commit hook for secrets

main() {
    local root_dir_path
    root_dir_path="$(git rev-parse --show-toplevel)"
    local trufflehog_output
    trufflehog_output="$(trufflehog git file://"$root_dir_path" --since-commit HEAD --config="$root_dir_path/tools/utils/trufflehog-config.yml" --fail --filter-entropy=3.4 2> /dev/stdout)"
    local status=$?
    if [ ${status} -ne 0 ]
    then
        echo "$trufflehog_output" | less
    fi
    exit ${status}
}
main
