<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload31f820c6422490593575c2147a0aee88($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'rest_exception_invalidtokenexception' => '/Exceptions/InvalidTokenException.class.php',
            'rest_token' => '/Token.class.php',
            'rest_tokendao' => '/TokenDao.class.php',
            'rest_tokenfactory' => '/TokenFactory.class.php',
            'rest_tokenmanager' => '/TokenManager.class.php',
            'tuleap\\rest\\basicauthentication' => '/BasicAuthentication.class.php',
            'tuleap\\rest\\resourcesinjector' => '/ResourcesInjector.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload31f820c6422490593575c2147a0aee88');
// @codeCoverageIgnoreEnd