#!/usr/bin/perl
#
# $Id$
#
use DBI;

require("../include.pl");  # Include all the predefined functions

$admin_list = ("precision,fusion94,dtype,bigdisk"); # ?? not really useful anymore.

&db_connect;

#
# Is current server master ?
#
my $server_is_master = is_current_server_master();

push @alias_array, "# This file is autogenerated - Do not edit\n\n";
push @alias_array, "#   - The codex wide aliases (specific to codex) resides in this file\n";
push @alias_array, "#   - All system wide aliases remains in /etc/aliases\n\n";
push @alias_array, "# Codex wide aliases\n\n";
push @alias_array, "codex-contact:         codex-admin\n\n";
push @alias_array, "sourceforge:           codex-admin\n"; # deprecated user name
push @alias_array, "$sys_http_user:               codex-admin\n";
push @alias_array, "noreply:               \"|$codex_bin_prefix/gotohell\"\n";
push @alias_array, "undisclosed-recipients: \"|$codex_bin_prefix/gotohell\"\n"; # for phpWiki notifications...
push @alias_array, "webmaster:             codex-admin\n\n";

if($server_is_master) {
push @alias_array, "\n\n### Begin Mailing List Aliases ###\n\n";

# Determine the name of the mailman wrapper
$mm_wrapper = "$mailman_wrapper";

# Select mailing list that public or private but not 'Deleted'
$query = "SELECT list_name from mail_group_list where is_public IN (0,1)";
$c = $dbh->prepare($query);
$c->execute();
while(my ($list_name) = $c->fetchrow()) {
  $list_name =~ tr/A-Z/a-z/;
  $list_name =~ s/ //g;
  # Mailman 2.1 aliases
  push @alias_array, sprintf("%-50s%-10s","$list_name:", "\"|$mm_wrapper post $list_name\"\n");
  push @alias_array, sprintf("%-50s%-10s","$list_name-admin:", "\"|$mm_wrapper admin $list_name\"\n");
  push @alias_array, sprintf("%-50s%-10s","$list_name-bounces:", "\"|$mm_wrapper bounces $list_name\"\n");
  push @alias_array, sprintf("%-50s%-10s","$list_name-confirm:", "\"|$mm_wrapper confirm $list_name\"\n");
  push @alias_array, sprintf("%-50s%-10s","$list_name-join:", "\"|$mm_wrapper join $list_name\"\n");
  push @alias_array, sprintf("%-50s%-10s","$list_name-leave:", "\"|$mm_wrapper leave $list_name\"\n");
  push @alias_array, sprintf("%-50s%-10s","$list_name-owner:", "\"|$mm_wrapper owner $list_name\"\n");
  push @alias_array, sprintf("%-50s%-10s","$list_name-request:", "\"|$mm_wrapper request $list_name\"\n");
  push @alias_array, sprintf("%-50s%-10s","$list_name-subscribe:", "\"|$mm_wrapper subscribe $list_name\"\n");
  push @alias_array, sprintf("%-50s%-10s","$list_name-unsubscribe:", "\"|$mm_wrapper unsubscribe $list_name\"\n");
}
}



push @alias_array, "\n\n### Begin User Aliases ###\n\n";

$query = "SELECT user_name,email FROM user WHERE status = \"A\" OR status = \"R\"";

$c = $dbh->prepare($query);
$c->execute();
while(($username, $email) = $c->fetchrow()) {
	if ($email) {
		if (!($admin_list =~ /.*$username*./)) {
			push @alias_array, sprintf("%-50s%-10s","$username:", "$email\n");
		}
	}
}

write_array_file("$dump_dir/aliases", @alias_array);
