<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload83686524d0f7d44696ee06c3e0f165e1($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'referencealias_gitplugin' => '/referencealias_gitPlugin.class.php',
            'tuleap\\referencealiasgit\\dao' => '/ReferenceAliasGit/Dao.php',
            'tuleap\\referencealiasgit\\plugin\\plugindescriptor' => '/ReferenceAliasGit/Plugin/PluginDescriptor.php',
            'tuleap\\referencealiasgit\\plugin\\plugininfo' => '/ReferenceAliasGit/Plugin/PluginInfo.php',
            'tuleap\\referencealiasgit\\reference' => '/ReferenceAliasGit/Reference.php',
            'tuleap\\referencealiasgit\\referencesbuilder' => '/ReferenceAliasGit/ReferencesBuilder.php',
            'tuleap\\referencealiasgit\\referencesimporter' => '/ReferenceAliasGit/ReferencesImporter.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload83686524d0f7d44696ee06c3e0f165e1');
// @codeCoverageIgnoreEnd
