packages:  # all packages in subdirs of packages/ and components/  - 'packages/**'
  - "lib/frontend/**/"
  - "lib/test-utils/**/"
  - "src/scripts/*/"
  - "src/themes/common"
  - "src/themes/BurningParrot"
  - "src/themes/FlamingParrot"
  - "src/additional-packages/*/"
  - "plugins/*/"
  - "plugins/*/scripts/**/"
  - "plugins/*/tests/e2e/**/"
  - "plugins/tracker/grammar/"
  - "tests/e2e/**/"
  - "docs/slides/*/"
shared-workspace-lockfile: false
