packages:  # all packages in subdirs of packages/ and components/  - 'packages/**'
  - "lib/frontend/**/"
  - "lib/test-utils/**/"
  - "src/scripts/*/"
  - "src/scripts/main/src/tlp-doc/"
  - "src/themes/tlp"
  - "src/themes/common"
  - "src/themes/BurningParrot"
  - "src/themes/FlamingParrot"
  - "src/additional-packages/*/"
  - "plugins/*/"
  - "plugins/*/scripts/**/"
  - "plugins/mediawiki_standalone/additional-packages/mediawiki-mathoid/"
  - "plugins/tracker/grammar/"
  - "tests/e2e/**/"
shared-workspace-lockfile: false
