<?php
/**
 * Copyright (c) Enalean, 2021 - Present. All Rights Reserved.
 *
 * This file is a part of Tuleap.
 *
 * Tuleap is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Tuleap is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Tuleap. If not, see <http://www.gnu.org/licenses/>.
 */

declare(strict_types=1);

namespace unit;

use Mockery\Adapter\Phpunit\MockeryPHPUnitIntegration;
use PHPUnit\Framework\TestCase;
use Tuleap\Layout\BaseLayout;
use Tuleap\Request\NotFoundException;
use Tuleap\ScaledAgile\Adapter\Program\Plan\ProgramAdapter;
use Tuleap\ScaledAgile\DisplayProgramBacklogController;
use Tuleap\ScaledAgile\Program\Plan\BuildProgram;
use Tuleap\ScaledAgile\Program\Program;
use Tuleap\ScaledAgile\ProgramBacklogPresenter;
use Tuleap\Test\Builders\UserTestBuilder;

final class DisplayProgramBacklogControllerTest extends TestCase
{
    use MockeryPHPUnitIntegration;

    /**
     * @var \Mockery\LegacyMockInterface|\Mockery\MockInterface|\TemplateRenderer
     */
    private $template_renderer;

    /**
     * @var DisplayProgramBacklogController
     */
    private $controller;
    /**
     * @var ProgramAdapter
     */
    private $build_program;
    /**
     * @var \Mockery\LegacyMockInterface|\Mockery\MockInterface|\ProjectManager
     */
    private $project_manager;

    protected function setUp(): void
    {
        $this->project_manager       = \Mockery::mock(\ProjectManager::class);
        $this->build_program         = \Mockery::mock(BuildProgram::class);
        $this->template_renderer     = \Mockery::mock(\TemplateRenderer::class);

        $this->controller = new DisplayProgramBacklogController(
            $this->project_manager,
            $this->build_program,
            $this->template_renderer
        );
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testItThrowsExceptionWhenServiceIsNotAvailable(): void
    {
        $project = \Mockery::mock(\Project::class);
        $project->shouldReceive('usesService')->once()->with(\scaled_agilePlugin::SERVICE_SHORTNAME)->andReturnFalse();
        $this->project_manager->shouldReceive('getProjectByUnixName')->once()->andReturn($project);

        $this->expectException(NotFoundException::class);

        $request   = \Mockery::mock(\HTTPRequest::class);
        $layout    = \Mockery::mock(BaseLayout::class);
        $variables = ['project_name' => 'test_project'];

        $this->controller->process($request, $layout, $variables);
    }

    public function testItDisplayProgramBacklog(): void
    {
        $project = \Mockery::mock(\Project::class);
        $project->shouldReceive('usesService')->once()->with(\scaled_agilePlugin::SERVICE_SHORTNAME)->andReturnTrue();
        $project->shouldReceive('getId')->andReturn(101);
        $project->shouldReceive('getPublicName')->andReturn('test_project');
        $project->shouldReceive('getUnixNameLowerCase')->andReturn('test_project');
        $this->project_manager->shouldReceive('getProjectByUnixName')->andReturn($project);

        $request   = \Mockery::mock(\HTTPRequest::class);
        $user      = UserTestBuilder::aUser()->build();
        $request->shouldReceive('getCurrentUser')->andReturn($user);
        $this->build_program->shouldReceive('buildExistingProgramProject')
            ->with($project->getID(), $user)
            ->once()->andReturn(new Program(101));

        $layout    = \Mockery::mock(BaseLayout::class);
        $layout->shouldReceive('addCssAsset')->once();
        $layout->shouldReceive('header')->once();
        $layout->shouldReceive('includeFooterJavascriptFile')->once();
        $layout->shouldReceive('footer')
            ->once()
            ->with([]);

        $variables = ['project_name' => 'test_project'];

        $this->template_renderer->shouldReceive('renderToPage')->once()
            ->with('program-backlog', \Mockery::type(ProgramBacklogPresenter::class));

        $this->controller->process($request, $layout, $variables);
    }
}
