<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoloadd52275b430aca353c5171b73146507d4($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'teamforge_compat_trackerplugin' => '/teamforge_compat_trackerPlugin.class.php',
            'tuleap\\teamforgecompattracker\\plugin\\plugindescriptor' => '/TeamforgeCompatTracker/Plugin/PluginDescriptor.php',
            'tuleap\\teamforgecompattracker\\plugin\\plugininfo' => '/TeamforgeCompatTracker/Plugin/PluginInfo.php',
            'tuleap\\teamforgecompattracker\\reference\\artifactreference' => '/TeamforgeCompatTracker/Reference/ArtifactReference.php',
            'tuleap\\teamforgecompattracker\\reference\\trackerreference' => '/TeamforgeCompatTracker/Reference/TrackerReference.php',
            'tuleap\\teamforgecompattracker\\referencesimporter' => '/TeamforgeCompatTracker/ReferencesImporter.class.php',
            'tuleap\\teamforgecompattracker\\teamforgecompatdao' => '/TeamforgeCompatTracker/TeamforgeCompatDao.class.php',
            'tuleap\\teamforgecompattracker\\teamforgereferencesbuilder' => '/TeamforgeCompatTracker/TeamforgeReferencesBuilder.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoloadd52275b430aca353c5171b73146507d4');
// @codeCoverageIgnoreEnd
