<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload40e7e2f0638a107fd224c9e7efc97f1a($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'dynamic_credentialsplugin' => '/dynamic_credentialsPlugin.class.php',
            'tuleap\\dynamiccredentials\\credential\\credentialcreator' => '/Credential/CredentialCreator.php',
            'tuleap\\dynamiccredentials\\credential\\credentialdao' => '/Credential/CredentialDAO.php',
            'tuleap\\dynamiccredentials\\credential\\credentialidentifierextractor' => '/Credential/CredentialIdentifierExtractor.php',
            'tuleap\\dynamiccredentials\\credential\\credentialinvalidusernameexception' => '/Credential/CredentialInvalidUsernameException.php',
            'tuleap\\dynamiccredentials\\credential\\duplicatecredentialexception' => '/Credential/DuplicateCredentialException.php',
            'tuleap\\dynamiccredentials\\plugindescriptor' => '/Plugin/PluginDescriptor.php',
            'tuleap\\dynamiccredentials\\plugininfo' => '/Plugin/PluginInfo.php',
            'tuleap\\dynamiccredentials\\rest\\dynamiccredentialsresource' => '/REST/DynamicCredentialsResource.php',
            'tuleap\\dynamiccredentials\\rest\\resourcesinjector' => '/REST/ResourcesInjector.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload40e7e2f0638a107fd224c9e7efc97f1a');
// @codeCoverageIgnoreEnd
