<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload137c4caa3b5d8a526c0bfdd35053e8cb($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'dynamic_credentialsplugin' => '/dynamic_credentialsPlugin.class.php',
            'tuleap\\dynamiccredentials\\plugindescriptor' => '/Plugin/PluginDescriptor.php',
            'tuleap\\dynamiccredentials\\plugininfo' => '/Plugin/PluginInfo.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload137c4caa3b5d8a526c0bfdd35053e8cb');
// @codeCoverageIgnoreEnd
