DROP TABLE plugin_mediawiki_interwiki;
DELETE FROM service WHERE short_name = 'plugin_mediawiki';
DROP VIEW group_plugin;
DROP VIEW plugins;
DROP TABLE plugin_mediawiki_ugroup_mapping;
DROP TABLE plugin_mediawiki_tuleap_mwgroups;
DROP TABLE plugin_mediawiki_database;
DROP TABLE plugin_mediawiki_admin_options;
DROP TABLE plugin_mediawiki_site_restricted_features;
DROP TABLE plugin_mediawiki_access_control;
DROP TABLE plugin_mediawiki_version;
