<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload6da90f986128ccb5b4b67a1d81d01be1($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'captchaplugin' => '/captchaPlugin.class.php',
            'tuleap\\captcha\\client' => '/Captcha/Client.php',
            'tuleap\\captcha\\configuration' => '/Captcha/Configuration.php',
            'tuleap\\captcha\\configurationnotfoundexception' => '/Captcha/ConfigurationNotFoundException.php',
            'tuleap\\captcha\\configurationretriever' => '/Captcha/ConfigurationRetriever.php',
            'tuleap\\captcha\\dataaccessobject' => '/Captcha/DataAccessObject.php',
            'tuleap\\captcha\\plugin\\descriptor' => '/Captcha/Plugin/Descriptor.php',
            'tuleap\\captcha\\plugin\\info' => '/Captcha/Plugin/Info.php',
            'tuleap\\captcha\\registration\\presenter' => '/Captcha/Registration/Presenter.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload6da90f986128ccb5b4b67a1d81d01be1');
// @codeCoverageIgnoreEnd
