<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoloadfdc852f81db5d89ccae02f4566ee03ff($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'captchaplugin' => '/captchaPlugin.class.php',
            'tuleap\\captcha\\plugin\\descriptor' => '/Captcha/Plugin/Descriptor.php',
            'tuleap\\captcha\\plugin\\info' => '/Captcha/Plugin/Info.php',
            'tuleap\\captcha\\registration\\presenter' => '/Captcha/Registration/Presenter.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoloadfdc852f81db5d89ccae02f4566ee03ff');
// @codeCoverageIgnoreEnd
