export default [
    {
        unidiff_offset: 1,
        old_offset: 1,
        new_offset: 1,
        content: "",
    },
    {
        unidiff_offset: 2,
        old_offset: 2,
        new_offset: 2,
        content: "",
    },
    {
        unidiff_offset: 3,
        old_offset: 3,
        new_offset: 3,
        content: "",
    },
    {
        unidiff_offset: 4,
        old_offset: 4,
        new_offset: 4,
        content: "",
    },
    {
        unidiff_offset: 5,
        old_offset: 5,
        new_offset: 5,
        content: "",
    },
    {
        unidiff_offset: 6,
        old_offset: 6,
        new_offset: 6,
        content: "",
    },
    {
        unidiff_offset: 7,
        old_offset: 7,
        new_offset: 7,
        content: "",
    },
    {
        unidiff_offset: 8,
        old_offset: 8,
        new_offset: 8,
        content: "",
    },
    {
        unidiff_offset: 9,
        old_offset: 9,
        new_offset: 9,
        content: "",
    },
    {
        unidiff_offset: 10,
        old_offset: 10,
        new_offset: 10,
        content: "",
    },
    {
        unidiff_offset: 11,
        old_offset: 11,
        new_offset: 11,
        content: "",
    },
    {
        unidiff_offset: 12,
        old_offset: 12,
        new_offset: null,
        content: "",
    },
    {
        unidiff_offset: 13,
        old_offset: 13,
        new_offset: 12,
        content: "",
    },
    {
        unidiff_offset: 14,
        old_offset: 14,
        new_offset: 13,
        content: "",
    },
    {
        unidiff_offset: 15,
        old_offset: 15,
        new_offset: 14,
        content: "",
    },
    {
        unidiff_offset: 16,
        old_offset: 16,
        new_offset: 15,
        content: "",
    },
    {
        unidiff_offset: 17,
        old_offset: 17,
        new_offset: 16,
        content: "",
    },
    {
        unidiff_offset: 18,
        old_offset: 18,
        new_offset: 17,
        content: "",
    },
    {
        unidiff_offset: 19,
        old_offset: 19,
        new_offset: 18,
        content: "",
    },
    {
        unidiff_offset: 20,
        old_offset: 20,
        new_offset: 19,
        content: "",
    },
    {
        unidiff_offset: 21,
        old_offset: 21,
        new_offset: 20,
        content: "",
    },
    {
        unidiff_offset: 22,
        old_offset: 22,
        new_offset: 21,
        content: "",
    },
    {
        unidiff_offset: 23,
        old_offset: 23,
        new_offset: 22,
        content: "",
    },
    {
        unidiff_offset: 24,
        old_offset: 24,
        new_offset: 23,
        content: "",
    },
];
