<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload610c74d521d15ebeb29b76662ddf9247($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'create_test_envplugin' => '/create_test_envPlugin.class.php',
            'tuleap\\createtestenv\\createtestenvironment' => '/CreateTestEnv/CreateTestEnvironment.php',
            'tuleap\\createtestenv\\createtestproject' => '/CreateTestEnv/CreateTestProject.php',
            'tuleap\\createtestenv\\createtestprojectpresenter' => '/CreateTestEnv/CreateTestProjectPresenter.php',
            'tuleap\\createtestenv\\createtestuser' => '/CreateTestEnv/CreateTestUser.php',
            'tuleap\\createtestenv\\exception\\createtestenvexception' => '/CreateTestEnv/Exception/CreateTestEnvException.php',
            'tuleap\\createtestenv\\exception\\emailnotuniqueexception' => '/CreateTestEnv/Exception/EmailNotUniqueException.php',
            'tuleap\\createtestenv\\exception\\invalidinputexception' => '/CreateTestEnv/Exception/InvalidInputException.php',
            'tuleap\\createtestenv\\exception\\invalidprojectfullnameexception' => '/CreateTestEnv/Exception/InvalidProjectFullNameException.php',
            'tuleap\\createtestenv\\exception\\invalidprojectunixnameexception' => '/CreateTestEnv/Exception/InvalidProjectUnixNameException.php',
            'tuleap\\createtestenv\\exception\\invalidrealnameexception' => '/CreateTestEnv/Exception/InvalidRealNameException.php',
            'tuleap\\createtestenv\\exception\\projectimportfailureexception' => '/CreateTestEnv/Exception/ProjectImportFailureException.php',
            'tuleap\\createtestenv\\exception\\projectnotcreatedexception' => '/CreateTestEnv/Exception/ProjectNotCreatedException.php',
            'tuleap\\createtestenv\\exception\\unabletocreatetemporarydirectoryexception' => '/CreateTestEnv/Exception/UnableToCreateTemporaryDirectoryException.php',
            'tuleap\\createtestenv\\exception\\unabletowritefileexception' => '/CreateTestEnv/Exception/UnableToWriteFileException.php',
            'tuleap\\createtestenv\\plugin\\plugindescriptor' => '/CreateTestEnv/Plugin/PluginDescriptor.php',
            'tuleap\\createtestenv\\plugin\\plugininfo' => '/CreateTestEnv/Plugin/PluginInfo.php',
            'tuleap\\createtestenv\\rest\\createtestenvresource' => '/CreateTestEnv/REST/CreateTestEnvResource.php',
            'tuleap\\createtestenv\\rest\\resourcesinjector' => '/CreateTestEnv/REST/ResourcesInjector.php',
            'tuleap\\createtestenv\\rest\\testenvironmentrepresentation' => '/CreateTestEnv/REST/TestEnvironmentRepresentation.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload610c74d521d15ebeb29b76662ddf9247');
// @codeCoverageIgnoreEnd
