<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload8d716e1eb67708d0f6b66667a3714f67($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'encryption_manager' => '/Encryption_Manager.class.php',
            'tracker_encryptionexception' => '/TrackerEncryption/Tracker_EncryptionException.class.php',
            'tracker_encryptionkeysettings_presenter' => '/EncryptionKeySettings_Presenter.class.php',
            'tracker_encryptionplugin' => '/tracker_encryptionPlugin.class.php',
            'tracker_formelement_field_encrypted' => '/Tracker_FormElement_Field_Encrypted.class.php',
            'tracker_key' => '/Tracker_Key.class.php',
            'trackerpublickeydao' => '/dao/Tracker_Public_KeyDao.class.php',
            'tuleap\\trackerencryption\\plugin\\plugindescriptor' => '/TrackerEncryption/Plugin/PluginDescriptor.php',
            'tuleap\\trackerencryption\\plugin\\plugininfo' => '/TrackerEncryption/Plugin/PluginInfo.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload8d716e1eb67708d0f6b66667a3714f67');
// @codeCoverageIgnoreEnd
