<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload1ff4d6f8d811917f9ef0f50164754663($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'openidconnectclientplugin' => '/openidconnectclientPlugin.class.php',
            'openidconnectclientplugindescriptor' => '/OpenIDConnectClientPluginDescriptor.class.php',
            'openidconnectclientplugininfo' => '/OpenIDConnectClientPluginInfo.class.php',
            'tuleap\\openidconnectclient\\flow' => '/OpenIDConnectClient/Flow.php',
            'tuleap\\openidconnectclient\\logincontroller' => '/OpenIDConnectClient/LoginController.php',
            'tuleap\\openidconnectclient\\provider\\provider' => '/OpenIDConnectClient/Provider/Provider.php',
            'tuleap\\openidconnectclient\\provider\\providerdao' => '/OpenIDConnectClient/Provider/ProviderDao.php',
            'tuleap\\openidconnectclient\\provider\\providermanager' => '/OpenIDConnectClient/Provider/ProviderManager.php',
            'tuleap\\openidconnectclient\\provider\\providernotfoundexception' => '/OpenIDConnectClient/Provider/ProviderNotFoundException.php',
            'tuleap\\openidconnectclient\\router' => '/OpenIDConnectClient/Router.php',
            'tuleap\\openidconnectclient\\usermapping\\usermapping' => '/OpenIDConnectClient/UserMapping/UserMapping.php',
            'tuleap\\openidconnectclient\\usermapping\\usermappingdao' => '/OpenIDConnectClient/UserMapping/UserMappingDao.class.php',
            'tuleap\\openidconnectclient\\usermapping\\usermappingmanager' => '/OpenIDConnectClient/UserMapping/UserMappingManager.php',
            'tuleap\\openidconnectclient\\usermapping\\usermappingnotfoundexception' => '/OpenIDConnectClient/UserMapping/UserMappingNotFoundException.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload1ff4d6f8d811917f9ef0f50164754663');
// @codeCoverageIgnoreEnd
