#!/usr/bin/php
<?php

try {
    ini_set('include_path', '/usr/share/pear:/usr/share/codendi/src/www/include:/usr/share/codendi/src:.');
    require_once 'pre.php';
    require_once 'common/svn/SVN_CommitMessage.class.php';

    $repository         = $argv[1];
    $propname           = $argv[4];
    $action             = $argv[5];
    $new_commit_message = stream_get_contents(STDIN);

    $svn_commit_message = new SVN_CommitMessage(ProjectManager::instance(), ReferenceManager::instance());
    $svn_commit_message->assertCanBeModified($repository, $action, $propname, $new_commit_message);
    exit(0);
} catch(Exception $e) {
    fwrite(STDERR, $e->getMessage().PHP_EOL);
    exit(1);
}

?>