-- Copyright© STMicroelectronics, 2006
-- Originally written by Manuel VACELET, STMicroelectronics, 2006 
--
-- This file is a part of CodeX.
--
-- CodeX is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- CodeX is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with CodeX; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
--
-- $Id$
--
-- Database upgrade script (see dbXXXX_template for instructions)
--
-- This SQL script allows you to upgrade the CodeX database. In most cases
-- this sql script relates to a well indentified modification in the 
-- CodeX source code. All references are included
-- below.
--
-- Description:
-- Phpwiki 1.3.12 require a new column.
--
-- References:
--
-- Dependencies:
-- 
-- SQL script comes next...
--

ALTER TABLE wiki_page ADD cached_html MEDIUMBLOB;
