# This compose file is provided for test purpose as:
# * the database is part of this compose file and that's not suitable for production
# * password are either hardcoded to dumb value or not existent (redis)
#
# You should have a .env file with those variables defined:
# TULEAP_FQDN
# MYSQL_ROOT_PASSWORD
# MYSQL_TULEAPADM_PASSWORD
# SITE_ADMINISTRATOR_PASSWORD
# See https://docs.docker.com/compose/environment-variables/

services:
  web:
    image: tuleap/tuleap-community-edition
    command: ["--debug"]
    hostname: ${TULEAP_FQDN}
    ports:
      - "443:443"
      - "3939:22"
    volumes:
      # For Tuleap devs, un-comment if you want to test stuff with your own code base
      - ../../../:/usr/share/tuleap:ro,cached
      - tuleap-data:/data
    depends_on:
      - db
      - mailhog
    environment:
      - TULEAP_FQDN=${TULEAP_FQDN}
      - TULEAP_SYS_DBHOST=db
      - TULEAP_SYS_DBPASSWD=${MYSQL_TULEAPADM_PASSWORD}
      - SITE_ADMINISTRATOR_PASSWORD=${SITE_ADMINISTRATOR_PASSWORD}
      - DB_ADMIN_USER=root
      - DB_ADMIN_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TULEAP_EMAIL_RELAYHOST=mailhog:1025
      - TULEAP_GIT_SSH_URL=ssh://gitolite@%server_name%:3939/
      #- TULEAP_GIT_SSH_URL=

  # This is for test purpose only. It's not advised to run a production database as a docker container
  db:
    image: mysql:8.0
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--sql-mode=NO_ENGINE_SUBSTITUTION"]
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db80-data:/var/lib/mysql

  # This is for test purpose only. Mailhog is there to capture email traffic
  mailhog:
    image: mailhog/mailhog

volumes:
  tuleap-data:
  db80-data:
