<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoloadcdc175ee9e17f8478687543178f30af1($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'hudson_svnplugin' => '/hudson_svnPlugin.class.php',
            'tuleap\\hudsonsvn\\plugin\\hudsonsvnplugindescriptor' => '/HudsonSvnPluginDescriptor.php',
            'tuleap\\hudsonsvn\\plugin\\hudsonsvnplugininfo' => '/HudsonSvnPluginInfo.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoloadcdc175ee9e17f8478687543178f30af1');
// @codeCoverageIgnoreEnd
