<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload5d8165d587a114daf2257e3b359b432a($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'hudson_svnplugin' => '/hudson_svnPlugin.class.php',
            'tuleap\\hudsonsvn\\continuousintegrationcollector' => '/ContinuousIntegrationCollector.php',
            'tuleap\\hudsonsvn\\formpresenter' => '/FormPresenter.php',
            'tuleap\\hudsonsvn\\job\\dao' => '/Job/Dao.php',
            'tuleap\\hudsonsvn\\job\\factory' => '/Job/Factory.php',
            'tuleap\\hudsonsvn\\job\\job' => '/Job/Job.php',
            'tuleap\\hudsonsvn\\job\\launcher' => '/Job/Launcher.php',
            'tuleap\\hudsonsvn\\job\\manager' => '/Job/Manager.php',
            'tuleap\\hudsonsvn\\plugin\\hudsonsvnplugindescriptor' => '/HudsonSvnPluginDescriptor.php',
            'tuleap\\hudsonsvn\\plugin\\hudsonsvnplugininfo' => '/HudsonSvnPluginInfo.php',
            'tuleap\\hudsonsvn\\svnbackendlogger' => '/SvnBackendLogger.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload5d8165d587a114daf2257e3b359b432a');
// @codeCoverageIgnoreEnd
