<?php
//
// CodeX: Breaking Down the Barriers to Source Code Sharing inside Xerox
// Copyright (c) Xerox Corporation, CodeX / CodeX Team, 2004. All Rights Reserved
// http://codex.xerox.com
//
// $Id$
//
//	Originally written by Laurent Julliard 2004, CodeX Team, Xerox
//


// CAUTION!!
// Make the changes before calling svn_header_admin because 
// svn_header_admin caches the project object in memory and
// the form values are therefore not updated.
//
if ($post_changes) {
    $ret = svn_data_update_general_settings($group_id,$form_tracked,$form_preamble);
    if ($ret) {
	$GLOBALS['feedback'] = "General Settings updated succesfully";
    } else {
	$GLOBALS['feedback'] = "General Settings update failed: ".db_error();
    }
}

// Display the form
svn_header_admin(array ('title'=>'Subversion Administration - General Settings',
		      'help' => 'SubversionAdministrationInterface.html#SubversionGeneralSettings'));

$project=project_get_object($group_id);
$svn_tracked = $project->isSVNTracked();
$svn_preamble = $project->getSVNPreamble();

echo '
       <H2>Subversion Administration - General Settings</H2>
       <FORM ACTION="'. $PHP_SELF .'" METHOD="GET">
       <INPUT TYPE="HIDDEN" NAME="group_id" VALUE="'.$group_id.'">
       <INPUT TYPE="HIDDEN" NAME="func" VALUE="general_settings">
       <INPUT TYPE="HIDDEN" NAME="post_changes" VALUE="y">
       <h3> Subversion Tracking</H3><I>
       <p>When Subversion tracking is on, the commits (file change, addition and 
removal) are registered in the '.$GLOBALS['sys_name'].
    'database so that they can be browsed and searched. Else commits are not logged in the database</I>
       <p><b>Subversion Tracking</b>&nbsp;&nbsp;&nbsp;&nbsp;<SELECT name="form_tracked">
       <OPTION VALUE="1"'.(($svn_tracked == '1') ? ' SELECTED':'').'>on</OPTION>
       <OPTION VALUE="0"'.(($svn_tracked == '0') ? ' SELECTED':'').'>off</OPTION>       </SELECT></p>
       <br>
      <h3>Subversion Preamble</h3>
      <P>If you type a message below, it will display on your project <a href="/svn/?func=info&group_id='.$group_id.
    '">Subversion welcome page</a>  replacing the default welcome message generated by '.$GLOBALS['sys_name'].'. Your custom message should explain how to access the Subversion repository.<br>
       <br>(HTML tags allowed)<br>
       <BR>
       <TEXTAREA cols="70" rows="8" wrap="virtual" name="form_preamble">'.$svn_preamble.'</TEXTAREA>
        </p>
        <INPUT TYPE="SUBMIT" NAME="SUBMIT" VALUE="Submit"></p></FORM>';

svn_footer(array());
?>
