#!/usr/bin/env groovy

def actions

pipeline {
    agent {
        label 'docker'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Prepare') {
            steps {
                dir ('results') {
                    deleteDir()
                }
                script {
                    actions = load 'sources/tests/actions.groovy'
                    actions.prepareSources('nexus.enalean.com_readonly')
                }
            }
        }

        stage('E2E tests') {
            steps { script { actions.runEndToEndTests('full') } }
            post {
                always {
                    junit 'results/e2e/full/*.xml'
                    archiveArtifacts allowEmptyArchive: true, artifacts: 'results/'
                }
                failure {
                    mail to: 'crew@enalean.com',
                         subject: "${currentBuild.fullDisplayName} is broken",
                         body: "See ${env.BUILD_URL}"
                }
                unstable {
                    mail to: 'crew@enalean.com',
                         subject: "${currentBuild.fullDisplayName} is unstable",
                         body: "See ${env.BUILD_URL}"
                }
            }
        }
    }
}
