<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload29960f904c5d66be8cb252532059d8bc($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'ldap' => '/LDAP.class.php',
            'ldap_authenticationfailedexception' => '/LDAP_AuthenticationFailedException.class.php',
            'ldap_backendsvn' => '/LDAP_BackendSVN.class.php',
            'ldap_cleanupmanager' => '/LDAP_CleanUpManager.class.php',
            'ldap_directorycleanupdao' => '/LDAP_DirectoryCleanUpDao.class.php',
            'ldap_directorysynchronization' => '/LDAP_DirectorySynchronization.class.php',
            'ldap_groupmanager' => '/LDAP_GroupManager.class.php',
            'ldap_loginpresenter' => '/LoginPresenter.class.php',
            'ldap_projectdao' => '/LDAP_ProjectDao.class.php',
            'ldap_projectgroupdao' => '/LDAP_ProjectGroupDao.class.php',
            'ldap_projectgroupmanager' => '/LDAP_ProjectGroupManager.class.php',
            'ldap_projectmanager' => '/LDAP_ProjectManager.class.php',
            'ldap_searchpeople' => '/LDAP_SearchPeople.class.php',
            'ldap_searchpeopleresultpresenter' => '/LDAP_SearchPeopleResultPresenter.php',
            'ldap_svn_apache' => '/LDAP_SVN_Apache.class.php',
            'ldap_syncmail' => '/LDAP_SyncMail.class.php',
            'ldap_syncnotificationmanager' => '/LDAP_SyncNotificationManager.class.php',
            'ldap_syncremindernotificationmanager' => '/LDAP_SyncReminderNotificationManager.class.php',
            'ldap_user' => '/LDAP_User.class.php',
            'ldap_userdao' => '/LDAP_UserDao.class.php',
            'ldap_usergroupdao' => '/LDAP_UserGroupDao.class.php',
            'ldap_usergroupmanager' => '/LDAP_UserGroupManager.class.php',
            'ldap_usermanager' => '/LDAP_UserManager.class.php',
            'ldap_usernotfoundexception' => '/LDAP_UserNotFoundException.class.php',
            'ldap_usersync' => '/LDAP_UserSync.class.php',
            'ldap_usersync_orange' => '/LDAP_UserSync_Orange.class.php',
            'ldapplugin' => '/ldapPlugin.class.php',
            'ldapplugindescriptor' => '/LdapPluginDescriptor.class.php',
            'ldapplugininfo' => '/LdapPluginInfo.class.php',
            'ldapresult' => '/LDAPResult.class.php',
            'ldapresultiterator' => '/LDAPResult.class.php',
            'systemevent_plugin_ldap_update_login' => '/system_event/SystemEvent_PLUGIN_LDAP_UPDATE_LOGIN.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload29960f904c5d66be8cb252532059d8bc');
// @codeCoverageIgnoreEnd