/**
 * CodeX: Breaking Down the Barriers to Source Code Sharing
 *
 * Copyright (c) Xerox Corporation, CodeX, 2007. All Rights Reserved
 *
 * This file is licensed under the CodeX Component Software License
 *
 * @author Anne Hardyau
 * @author Marc Nazarian
 */

package com.xerox.xrce.codex.jri.model.tracker;

import com.xerox.xrce.codex.jri.model.CxFromServer;
import com.xerox.xrce.codex.jri.model.CxServer;
import com.xerox.xrce.codex.jri.model.wsproxy.ArtifactFieldValue;

/**
 * CxArtifactFieldValue is the class for field value
 * 
 */
public class CxArtifactFieldValue extends CxFromServer {

    /**
     * The ArtifactFieldValue Object (generated by WSDL2JAVA)
     */
    private ArtifactFieldValue artifactFieldValue;

    /**
     * Constructor from ArtifactFieldValue Object)
     * 
     * @param server the server this field value belongs to
     * @param artifactFieldValue the ArtifactFieldValue Object
     */
    public CxArtifactFieldValue(CxServer server,
            ArtifactFieldValue artifactFieldValue) {
        super(server);
        this.artifactFieldValue = artifactFieldValue;
    }

    /**
     * Returns the ID of the field of this value
     * 
     * @return the ID of the field of this value
     */
    public int getFieldID() {
        return artifactFieldValue.getField_id();
    }

    /**
     * Returns the value of this field value
     * 
     * @return the value of this field value
     */
    public String getFieldValue() {
        return artifactFieldValue.getField_value();
    }

}
