/**
 * CodeX: Breaking Down the Barriers to Source Code Sharing
 *
 * Copyright (c) Xerox Corporation, CodeX, 2007. All Rights Reserved
 *
 * This file is licensed under the CodeX Component Software License
 *
 * @author Anne Hardyau
 * @author Marc Nazarian
 */

package com.xerox.xrce.codex.jri.model.tracker;

import com.xerox.xrce.codex.jri.model.CxFromServer;
import com.xerox.xrce.codex.jri.model.CxServer;
import com.xerox.xrce.codex.jri.model.wsproxy.ArtifactReportField;

/**
 * CxArtifactReportField is the class for field in reports.
 * 
 */
public class CxArtifactReportField extends CxFromServer {

    /**
     * The ArtifactReportField Object (generated by WSDL2JAVA)
     */
    private ArtifactReportField artifactReportField;

    /**
     * Constructor from ArtifactReportField Object
     * 
     * @param server the server the report field belongs to
     * @param artifactReportField the ArtifactReportField Object
     */
    public CxArtifactReportField(CxServer server,
            ArtifactReportField artifactReportField) {
        super(server);
        this.artifactReportField = artifactReportField;
    }

    /**
     * Returns the name of this report field
     * 
     * @return the name of this report field
     */
    public String getName() {
        return artifactReportField.getField_name();
    }

    /**
     * Determine if this report field is used (displayed) in result query
     * 
     * @return true if this report field is used in resutl query, false
     *         otherwise
     */
    public boolean isShownOnResult() {
        return (artifactReportField.getShow_on_result() == 1);
    }

    /**
     * Returns the width of this report field in the result (in number of
     * caracters)
     * 
     * @return the width of this report field in the result (in number of
     *         caracters)
     */
    public int getColWidth() {
        return artifactReportField.getCol_width();
    }

    /**
     * Determine if this report field is used as a field in the query
     * 
     * @return true if this report field is used as a field in the query, false
     *         otherwise
     */
    public boolean isShownOnQuery() {
        return (artifactReportField.getShow_on_query() == 1);
    }

}
