/**
 * CodeX: Breaking Down the Barriers to Source Code Sharing
 *
 * Copyright (c) Xerox Corporation, CodeX, 2007. All Rights Reserved
 *
 * This file is licensed under the CodeX Component Software License
 *
 * @author Anne Hardyau
 * @author Marc Nazarian
 */

package com.xerox.xrce.codex.jri.model.tracker;

import com.xerox.xrce.codex.jri.model.CxFromServer;
import com.xerox.xrce.codex.jri.model.CxServer;
import com.xerox.xrce.codex.jri.model.wsproxy.ArtifactRule;

/**
 * CxArtifactFieldDependenciesRule is the class for field dependencies. Field
 * dependencies are link between the values of two fields. You can set you
 * tracker some rules saying that a given value for a given field will allow
 * others value for another field.
 * 
 */
public class CxArtifactFieldDependenciesRule extends CxFromServer {

    /**
     * The Artifactrule Object (generated by WSDL2JAVA)
     */
    private ArtifactRule artifactRule;

    /**
     * Constructor from the ArtifactRule Object
     * 
     * @param server the server the rule belongs to
     * @param artifactRule the ArtifactRule Object
     */
    public CxArtifactFieldDependenciesRule(CxServer server,
            ArtifactRule artifactRule) {
        super(server);
        this.artifactRule = artifactRule;
    }

    /**
     * Returns the ID of this rule
     * 
     * @return the Id of this rule
     */
    public int getID() {
        return this.artifactRule.getRule_id();
    }

    /**
     * Returns the Id of the source field of this rule
     * 
     * @return the Id of the source field of this rule
     */
    public int getSourceFieldID() {
        return this.artifactRule.getSource_field_id();
    }

    /**
     * Returns the Id of the value of the source field of this rule
     * 
     * @return the Id of the value of the source field of this rule
     */
    public int getSourceValueID() {
        return this.artifactRule.getSource_value_id();
    }

    /**
     * Returns the Id of the target field of this rule
     * 
     * @return the Id of the target field of this rule
     */
    public int getTargetFieldID() {
        return this.artifactRule.getTarget_field_id();
    }

    /**
     * Returns the Id of the value of the target field of this rule
     * 
     * @return the Id of the value of the target field of this rule
     */
    public int getTargetValueID() {
        return this.artifactRule.getTarget_value_id();
    }
}
