/**
 * CodeX: Breaking Down the Barriers to Source Code Sharing
 *
 * Copyright (c) Xerox Corporation, CodeX, 2007. All Rights Reserved
 *
 * This file is licensed under the CodeX Component Software License
 *
 * @author Anne Hardyau
 * @author Marc Nazarian
 */

package com.xerox.xrce.codex.jri.model.tracker;

import com.xerox.xrce.codex.jri.model.CxFromServer;
import com.xerox.xrce.codex.jri.model.CxServer;
import com.xerox.xrce.codex.jri.model.wsproxy.ArtifactFollowup;

/**
 * CxArtifactFollowUp is the class for follow-up comments of artifact.
 * 
 */
public class CxArtifactFollowUp extends CxFromServer {

    /**
     * The ArtifactFollowup Object (generated by WSDL2JAVA)
     */
    private ArtifactFollowup artifactFollowUp;

    /**
     * Constructor from an ArtifactFollowup Object
     * 
     * @param server the server the follow-up belongs to
     * @param artifactFollowup the ArtifactFollowup object
     */
    public CxArtifactFollowUp(CxServer server, ArtifactFollowup artifactFollowup) {
        super(server);
        this.artifactFollowUp = artifactFollowup;
    }

    /**
     * Returns the comment of this follow-up (the message)
     * 
     * @return the comment of this follow-up
     */
    public String getComment() {
        return artifactFollowUp.getComment();
    }

    /**
     * Returns the date this follow-up has been posted (unix time stamp)
     * 
     * @return the date this follow-up has been posted (unix time stamp)
     */
    public int getDate() {
        return artifactFollowUp.getDate();
    }

    /**
     * Returns the name of the user who has posted the follow-up
     * 
     * @return the name of the user who has posted the follow-up
     */
    public String getBy() {
        return artifactFollowUp.getBy();
    }

    /**
     * Test if this follow-up has a comment type or not
     * 
     * @return true of this follow-up has a comment type, false otherwise
     */
    public boolean hasCommentType() {
        return artifactFollowUp.getComment_type_id() != 100
               && artifactFollowUp.getComment_type() != null
               && !"".equals(artifactFollowUp.getComment_type());
    }

    /**
     * Returns the comment type of this follow-up
     * 
     * @return the comment type of this follow-up
     */
    public String getCommentType() {
        return artifactFollowUp.getComment_type();
    }

}
