/**
 * CodeX: Breaking Down the Barriers to Source Code Sharing
 *
 * Copyright (c) Xerox Corporation, CodeX, 2007. All Rights Reserved
 *
 * This file is licensed under the CodeX Component Software License
 *
 * @author Anne Hardyau
 * @author Marc Nazarian
 */

package com.xerox.xrce.codex.jri.model.tracker;

import com.xerox.xrce.codex.jri.model.CxFromServer;
import com.xerox.xrce.codex.jri.model.CxServer;
import com.xerox.xrce.codex.jri.model.wsproxy.ArtifactHistory;

/**
 * CxArtifactHistory is the class for the artifact history. The history keep the
 * changes of fields value of artifacts.
 * 
 */
public class CxArtifactHistory extends CxFromServer {

    /**
     * The ArtifactHistory Object (generated by WSDL2JAVA)
     */
    private ArtifactHistory artifactHistory;

    /**
     * Constructor from ArtifactHistory Object
     * 
     * @param server the server the artifact history belongs to
     * @param artifactHistory the ArtifactHistory Object
     */
    public CxArtifactHistory(CxServer server, ArtifactHistory artifactHistory) {
        super(server);
        this.artifactHistory = artifactHistory;
    }

    /**
     * Returns the name of the field of this history item
     * 
     * @return the name of the field of this artifact history
     */
    public String getFieldName() {
        return artifactHistory.getField_name();
    }

    /**
     * Returns the old value of this artifact history
     * 
     * @return the old value of this artifact history
     */
    public String getOldValue() {
        return artifactHistory.getOld_value();
    }

    /**
     * Returns the new value of this artifact history
     * 
     * @return the new value of this artifact history
     */
    public String getNewValue() {
        return artifactHistory.getNew_value();
    }

    /**
     * Returns the date where the field has been changed for this artifact
     * history (unix time stamp)
     * 
     * @return the date where the field has been changed for this artifact
     *         history (unix time stamp)
     */
    public int getDate() {
        return artifactHistory.getDate();
    }

    /**
     * Returns the name of the user who changed the field for this artifact
     * history
     * 
     * @return the name of the user who changed the field for this artifact
     *         history
     */
    public String getModificationBy() {
        return artifactHistory.getModification_by();
    }

}
