<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoloada642adaae64d59ed6289cf0ac96745c5($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'teamforge_compat_mediawikiplugin' => '/teamforge_compat_mediawikiPlugin.class.php',
            'tuleap\\teamforgecompatmediawiki\\compatibilitydao' => '/CompatibilityDao.php',
            'tuleap\\teamforgecompatmediawiki\\plugin\\plugindescriptor' => '/TeamForgeCompatMediawiki/Plugin/PluginDescriptor.php',
            'tuleap\\teamforgecompatmediawiki\\plugin\\plugininfo' => '/TeamForgeCompatMediawiki/Plugin/PluginInfo.php',
            'tuleap\\teamforgecompatmediawiki\\referencesbuilder' => '/ReferencesBuilder.php',
            'tuleap\\teamforgecompatmediawiki\\referencesimporter' => '/ReferencesImporter.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoloada642adaae64d59ed6289cf0ac96745c5');
// @codeCoverageIgnoreEnd
