<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload876df377455ad721c5fad5b53fab0b65($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'teamforge_compat_mediawikiplugin' => '/teamforge_compat_mediawikiPlugin.class.php',
            'tuleap\\teamforgecompatmediawiki\\plugin\\plugindescriptor' => '/TeamForgeCompatMediawiki/Plugin/PluginDescriptor.php',
            'tuleap\\teamforgecompatmediawiki\\plugin\\plugininfo' => '/TeamForgeCompatMediawiki/Plugin/PluginInfo.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload876df377455ad721c5fad5b53fab0b65');
// @codeCoverageIgnoreEnd
