INSERT INTO tracker (id,
    group_id,
    name,
    description,
    item_name,
    allow_copy,
    submit_instructions,
    browse_instructions,
    status,
    deletion_date,
    instantiate_for_new_projects,
    stop_notification)
SELECT group_artifact_id,
    group_id,
    REPLACE(REPLACE(name, '&gt;', '>'), '&lt;', '<'),
    REPLACE(REPLACE(description, '&gt;', '>'), '&lt;', '<'),
    item_name,
    allow_copy,
    submit_instructions,
    browse_instructions,
    status,
    deletion_date,
    instantiate_for_new_projects,
    stop_notification
FROM artifact_group_list;

