<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload3ad4c29c825e96f6b58db21c8ef76c74($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'databaseinitialization' => '/DatabaseInitialisation.class.php',
            'errordataaccessresult' => '/TestHelper.class.php',
            'fakedataaccessresult' => '/TestHelper.class.php',
            'filtertestcase' => '/FilterTestCase.php',
            'filtertestdirectory' => '/FilterTestDirectory.php',
            'simplemockongoinginterlligentstub' => '/SimpleMockOngoingInterlligentStub.php',
            'testdatabuilder' => '/TestDataBuilder.php',
            'testhelper' => '/TestHelper.class.php',
            'tuleap\\test\\mockeryongoingintelligentstub' => '/MockeryOngoingIntelligentStub.php',
            'tuleapdbtestcase' => '/TuleapDbTestCase.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload3ad4c29c825e96f6b58db21c8ef76c74');
// @codeCoverageIgnoreEnd
