<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload5989d8a7f220638e6cd55be72029c54b($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'databaseinitialization' => '/DatabaseInitialisation.class.php',
            'dbtestaccess' => '/DBTestAccess.php',
            'fakedataaccessresult' => '/TestHelper.class.php',
            'ongoingintelligentstub' => '/MockBuilder.php',
            'restbase' => '/rest/RestBase.php',
            'soap_databaseinitialization' => '/soap/SOAP_DatabaseInitialization.php',
            'soap_testdatabuilder' => '/soap/SOAP_TestDataBuilder.php',
            'soapbase' => '/soap/SOAPBase.php',
            'test\\rest\\requestwrapper' => '/rest/RequestWrapper.php',
            'test\\rest\\tracker\\tracker' => '/rest/tracker/Tracker.php',
            'test\\rest\\tracker\\trackerfactory' => '/rest/tracker/TrackerFactory.php',
            'testdatabuilder' => '/rest/TestDataBuilder.php',
            'testhelper' => '/TestHelper.class.php',
            'tuleapdbtestcase' => '/TuleapDbTestCase.class.php',
            'tuleaptestcase' => '/TuleapTestCase.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload5989d8a7f220638e6cd55be72029c54b');
// @codeCoverageIgnoreEnd
