<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload17fc329a8482b2cf98cbaf06c4537e1b($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'markdownplugin' => '/markdownPlugin.class.php',
            'markdownplugindescriptor' => '/MarkdownPluginDescriptor.class.php',
            'markdownplugininfo' => '/MarkdownPluginInfo.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload17fc329a8482b2cf98cbaf06c4537e1b');
// @codeCoverageIgnoreEnd