<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoloadf3f40fd17a877aad6bdeb58c89126c83($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'mediawikidao' => '/MediawikiDao.class.php',
            'mediawikigroupsmapper' => '/MediawikiGroupsMapper.class.php',
            'mediawikiinstantiater' => '/MediawikiInstantiater.class.php',
            'mediawikiplugin' => '/mediawikiPlugin.class.php',
            'mediawikiplugindescriptor' => '/MediaWikiPluginDescriptor.class.php',
            'mediawikiplugininfo' => '/MediaWikiPluginInfo.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoloadf3f40fd17a877aad6bdeb58c89126c83');
// @codeCoverageIgnoreEnd