SHELL=/usr/bin/env bash

generate-templates:
	xsltproc $(CURDIR)/../../tools/utils/setup_templates/generate-templates/generate-scrum_dashboard.xml \
		-o resources/templates/scrum_dashboard_template.xml
