generate-templates:
	xsltproc $(CURDIR)/../../tools/utils/setup_templates/generate-templates/generate-scrum_dashboard.xml \
		-o resources/templates/scrum_dashboard_template.xml
	cp -f $(CURDIR)/../../tools/utils/setup_templates/generate-templates/trackers/activity.xml \
		resources/templates/Tracker_activity.xml
