<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload58721627b8b783fd7409f23d858bf4b9($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'tuleap\\token\\rest\\tokenrepresentation' => '/REST/TokenRepresentation.class.php',
            'tuleap\\token\\rest\\tokenuserauthrepresentation' => '/REST/TokenUserAuthRepresentation.class.php',
            'tuleap\\token\\rest\\v1\\tokenresource' => '/REST/v1/TokenResource.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload58721627b8b783fd7409f23d858bf4b9');
// @codeCoverageIgnoreEnd