FROM centos:7

RUN yum install -y epel-release https://rpms.remirepo.net/enterprise/remi-release-7.rpm && \
    yum install -y \
        git \
        php73-php-cli \
        php73-php-dom \
        php73-php-soap \
        php73-php-pdo \
        php73-php-sodium \
        php73-php-ldap \
        php73-php-intl \
        php73-php-pecl-redis \
        php73-php-pecl-zip \
        php73-php-pecl-igbinary \
        php73-php-mysqlnd
