<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload68a8ea8e828d419400b7c8a12e12492d($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'teamforge_compat_coreplugin' => '/teamforge_compat_corePlugin.class.php',
            'tuleap\\teamforgecompatcore\\plugin\\plugindescriptor' => '/TeamforgeCompatCore/Plugin/PluginDescriptor.php',
            'tuleap\\teamforgecompatcore\\plugin\\plugininfo' => '/TeamforgeCompatCore/Plugin/PluginInfo.php',
            'tuleap\\teamforgecompatcore\\referencesimporter' => '/TeamforgeCompatCore/ReferencesImporter.class.php',
            'tuleap\\teamforgecompatcore\\teamforgecompatdao' => '/TeamforgeCompatCore/TeamforgeCompatDao.class.php',
            'tuleap\\teamforgecompatcore\\teamforgereferencesbuilder' => '/TeamforgeCompatCore/TeamforgeReferencesBuilder.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload68a8ea8e828d419400b7c8a12e12492d');
// @codeCoverageIgnoreEnd
