<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoloadd9bae642e38a93a944442f11d0723d9e($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'proftpd\\xferlog\\entry' => '/ProFTPd/Xferlog/Entry.class.php',
            'proftpd\\xferlog\\invalidentryexception' => '/ProFTPd/Xferlog/InvalidEntryException.class.php',
            'proftpd\\xferlog\\parser' => '/ProFTPd/Xferlog/Parser.class.php',
            'proftpdplugin' => '/proftpdPlugin.class.php',
            'proftpdplugindescriptor' => '/ProftpdPluginDescriptor.class.php',
            'proftpdplugininfo' => '/ProftpdPluginInfo.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoloadd9bae642e38a93a944442f11d0723d9e');
// @codeCoverageIgnoreEnd