<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoloade3dd183e9082cbb6b866d4281d05f5ba($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'proftpd_directory_directoryitem' => '/Directory/DirectoryItem.class.php',
            'proftpd_directory_directoryparser' => '/Directory/DirectoryParser.class.php',
            'proftpd_directory_directorypathcollection' => '/Directory/DirectoryPathCollection.class.php',
            'proftpd_directory_directorypathparser' => '/Directory/DirectoryPathParser.class.php',
            'proftpd_directory_directorypathpart' => '/Directory/DirectoryPathPart.class.php',
            'proftpd_explorercontroller' => '/Explorer/ExplorerController.class.php',
            'proftpd_presenter_explorerpresenter' => '/Presenters/ExplorerPresenter.class.php',
            'proftpdplugin' => '/proftpdPlugin.class.php',
            'proftpdplugindescriptor' => '/ProftpdPluginDescriptor.class.php',
            'proftpdplugininfo' => '/ProftpdPluginInfo.class.php',
            'proftpdrouter' => '/ProftpdRouter.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoloade3dd183e9082cbb6b866d4281d05f5ba');
// @codeCoverageIgnoreEnd