<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload15c22fa0d7eb730d3e48fba1875cc9f6($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'hudson_gitplugin' => '/hudson_gitPlugin.class.php',
            'tuleap\\hudsongit\\hook\\hookcontroller' => '/HudsonGit/Hook/HookController.php',
            'tuleap\\hudsongit\\hook\\hookdao' => '/HudsonGit/Hook/HookDao.php',
            'tuleap\\hudsongit\\hook\\hookpresenter' => '/HudsonGit/Hook/HookPresenter.php',
            'tuleap\\hudsongit\\plugin\\plugindescriptor' => '/HudsonGit/Plugin/PluginDescriptor.php',
            'tuleap\\hudsongit\\plugin\\plugininfo' => '/HudsonGit/Plugin/PluginInfo.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload15c22fa0d7eb730d3e48fba1875cc9f6');
// @codeCoverageIgnoreEnd
