<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoloadb0338b250ab9b437df868e6d0dd17e5e($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'hudson_gitplugin' => '/hudson_gitPlugin.class.php',
            'tuleap\\hudsongit\\hook\\hookcontroller' => '/HudsonGit/Hook/HookController.php',
            'tuleap\\hudsongit\\hook\\hookdao' => '/HudsonGit/Hook/HookDao.php',
            'tuleap\\hudsongit\\hook\\hookpresenter' => '/HudsonGit/Hook/HookPresenter.php',
            'tuleap\\hudsongit\\hook\\hooktriggercontroller' => '/HudsonGit/Hook/HookTriggerController.php',
            'tuleap\\hudsongit\\logger' => '/Logger.php',
            'tuleap\\hudsongit\\plugin\\plugindescriptor' => '/HudsonGit/Plugin/PluginDescriptor.php',
            'tuleap\\hudsongit\\plugin\\plugininfo' => '/HudsonGit/Plugin/PluginInfo.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoloadb0338b250ab9b437df868e6d0dd17e5e');
// @codeCoverageIgnoreEnd
