<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoloadd50df0bfd2e8dbb13464cee60666568a($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'hudson_gitplugin' => '/hudson_gitPlugin.class.php',
            'tuleap\\hudsongit\\plugin\\plugindescriptor' => '/HudsonGit/Plugin/PluginDescriptor.php',
            'tuleap\\hudsongit\\plugin\\plugininfo' => '/HudsonGit/Plugin/PluginInfo.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoloadd50df0bfd2e8dbb13464cee60666568a');
// @codeCoverageIgnoreEnd
