#!/bin/sh
#
# CodeX: Breaking Down the Barriers to Source Code Sharing inside Xerox
# Copyright (c) Xerox Corporation, CodeX/CodeX Team, 2001-2004. All Rights Reserved
# http://codex.xerox.com
#
#
#  $Id$
#
#  License:
#    This file is subject to the terms and conditions of the GNU General Public
#    license. See the file COPYING in the main directory of this archive for
#    more details.
#
# /home/tools/backup_job
#
#      Originally written by Vicki Tuttle 2001- 2003, CodeX Team, Xerox
#      This job shuts down mysql and copies mysql database files to
#      /cvsroot/.mysql_backup
#      It then starts mysql and backs up all filesystems to tape
#
#     For this backup strategy to work properly the mysql log facility
#     must be activated in /etc/my.cnf and this job must be run
#     before the full system takes place.
#

set -e

###############################################################################
# Configuration Variables


## Global definitions
oldBackupDstDir=/cvsroot/.mysql_backup/old
currentBackupDstDir=/cvsroot/.mysql_backup
mysqlDataDir=/var/lib/mysql

#
###############################################################################


# if NOOLD=1 -> Old full backup is deleted instread of staying
# in a dedicated directory.
NOOLD=0

# Check arguments
while   ((1))   # look for options
do      case    "$1" in
        \-noarchives)   NOOLD=1;;
        *)      if [ ! -z "$1" ];
            then
                echo "Invalid option $1";
                HELP=1;
            fi
            break;;
        esac
        shift # next argument
done

MKDIR=/bin/mkdir
MV=/bin/mv
DUMP=/sbin/dump
RM=/bin/rm
# New archive directory
oldBackupDir=${oldBackupDstDir}/`date +%m%d%y`

/etc/init.d/mysqld stop
sleep 5

# Move current bkp to old dir
${MKDIR} -p ${oldBackupDir}

# Because of -e flag, we need to make sure the files exist before moving them
binfiles=`ls ${currentBackupDstDir} | grep codex-bin | head -1`
if [ $binfiles ];
then
    ${MV} ${currentBackupDstDir}/codex-bin.* ${oldBackupDir}
fi
dumpfiles=`ls ${currentBackupDstDir} | grep sqldump | head -1`
if [ $dumpfiles ];
then
    ${MV} ${currentBackupDstDir}/sqldump* ${oldBackupDir}
fi

# back up mysql datafiles to disk
${DUMP} 0f ${currentBackupDstDir}/sqldump.`date +%m%d%y.%H%M` -M ${mysqlDataDir}

# If there is no archives keeping, delete old  backup
if [ "${NOOLD}" == 1 ]; then 
    ${RM} -rf ${oldBackupDir}
fi

/etc/init.d/mysqld start
