<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoloadadcfb445355475f44e7427789b7ee56f($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'pagenameinvalidcharexception' => '/exceptions/PageNameInvalidCharException.class.php',
            'pagenametoolongexception' => '/exceptions/PageNameTooLongException.class.php',
            'paginatedphpwikipages' => '/lib/PaginatedPHPWikiPages.class.php',
            'paginatedphpwikipagesfactory' => '/lib/PaginatedPHPWikiPagesFactory.class.php',
            'phpwiki' => '/lib/PHPWiki.class.php',
            'phpwiki_permissionsmanager' => '/PermissionsManager.class.php',
            'phpwikiactions' => '/actions/PHPWikiActions.class.php',
            'phpwikiadminallowedprojectspresenter' => '/PHPWikiAdminAllowedProjectsPresenter.class.php',
            'phpwikiadmincontroller' => '/PHPWikiAdminController.class.php',
            'phpwikiadminmigrator' => '/PHPWikiAdminMigrator.class.php',
            'phpwikiadminmigratordao' => '/PHPWikiAdminMigratorDao.class.php',
            'phpwikiattachment' => '/lib/PHPWikiAttachment.class.php',
            'phpwikiattachmentdao' => '/lib/PHPWikiAttachmentDao.class.php',
            'phpwikiattachmentrevision' => '/lib/PHPWikiAttachmentRevision.class.php',
            'phpwikiattachmentrevisiondao' => '/lib/PHPWikiAttachmentRevisionDao.class.php',
            'phpwikicloner' => '/lib/PHPWikiCloner.class.php',
            'phpwikidao' => '/PHPWikiDao.class.php',
            'phpwikientry' => '/lib/PHPWikiEntry.class.php',
            'phpwikimigratordao' => '/migration/PHPWikiMigratorDao.class.php',
            'phpwikipage' => '/lib/PHPWikiPage.class.php',
            'phpwikipageversion' => '/lib/PHPWikiPageVersion.class.php',
            'phpwikipageversioncontentformatter' => '/lib/PHPWikiPageVersionContentFormatter.php',
            'phpwikipageversionfactory' => '/lib/PHPWikiPageVersionFactory.class.php',
            'phpwikipagewrapper' => '/lib/PHPWikiPageWrapper.class.php',
            'phpwikiplugin' => '/phpwikiPlugin.class.php',
            'phpwikiplugin_rest_resourcesinjector' => '/REST/v1/ResourcesInjector.class.php',
            'phpwikiplugindescriptor' => '/PHPWikiPluginDescriptor.class.php',
            'phpwikiplugininfo' => '/PHPWikiPluginInfo.class.php',
            'phpwikiservice' => '/PHPWikiService.class.php',
            'phpwikiserviceactions' => '/actions/PHPWikiServiceActions.class.php',
            'phpwikiserviceadmin' => '/PHPWikiServiceAdmin.class.php',
            'phpwikiserviceadminactions' => '/actions/PHPWikiServiceAdminActions.class.php',
            'phpwikiserviceadminviews' => '/views/PHPWikiServiceAdminViews.class.php',
            'phpwikiserviceviews' => '/views/PHPWikiServiceViews.class.php',
            'phpwikiversiondao' => '/PHPWikiVersionDao.class.php',
            'phpwikiviews' => '/views/PHPWikiViews.class.php',
            'systemevent_phpwiki_switch_to_plugin' => '/events/SystemEvent_PHPWIKI_SWITCH_TO_PLUGIN.class.php',
            'tuleap\\phpwiki\\rest\\v1\\phpwikipluginpagefullrepresentation' => '/REST/v1/PhpWikiPluginPageFullRepresentation.class.php',
            'tuleap\\phpwiki\\rest\\v1\\phpwikipluginpagerepresentation' => '/REST/v1/PhpWikiPluginPageRepresentation.class.php',
            'tuleap\\phpwiki\\rest\\v1\\phpwikipluginpageversionfullrepresentation' => '/REST/v1/PhpWikiPluginPageVersionFullRepresentation.class.php',
            'tuleap\\phpwiki\\rest\\v1\\phpwikipluginpageversionrepresentation' => '/REST/v1/PhpWikiPluginPageVersionRepresentation.class.php',
            'tuleap\\phpwiki\\rest\\v1\\phpwikipluginresource' => '/REST/v1/PhpWikiPluginResource.class.php',
            'tuleap\\phpwiki\\rest\\v1\\projectresource' => '/REST/v1/ProjectResource.class.php',
            'widgetpublicareapresenter' => '/presenters/WidgetPublicAreaPresenter.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoloadadcfb445355475f44e7427789b7ee56f');
// @codeCoverageIgnoreEnd
