<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload9c5aff42d030bfb55852230cdefb47ad($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'hudson' => '/hudson.class.php',
            'hudson_widget_jobbuildhistory' => '/hudson_Widget_JobBuildHistory.class.php',
            'hudson_widget_joblastartifacts' => '/hudson_Widget_JobLastArtifacts.class.php',
            'hudson_widget_joblastbuilds' => '/hudson_Widget_JobLastBuilds.class.php',
            'hudson_widget_jobtestresults' => '/hudson_Widget_JobTestResults.class.php',
            'hudson_widget_jobtesttrend' => '/hudson_Widget_JobTestTrend.class.php',
            'hudson_widget_mymonitoredjobs' => '/hudson_Widget_MyMonitoredJobs.class.php',
            'hudson_widget_projectjobsoverview' => '/hudson_Widget_ProjectJobsOverview.class.php',
            'hudsonactions' => '/hudsonActions.class.php',
            'hudsonbuild' => '/HudsonBuild.class.php',
            'hudsonjob' => '/HudsonJob.class.php',
            'hudsonjobfactory' => '/HudsonJobFactory.class.php',
            'hudsonjoburlfileexception' => '/HudsonJobURLFileException.class.php',
            'hudsonjoburlfilenotfoundexception' => '/HudsonJobURLFileNotFoundException.class.php',
            'hudsonjoburlmalformedexception' => '/HudsonJobURLMalformedException.class.php',
            'hudsonjobwidget' => '/HudsonJobWidget.class.php',
            'hudsonoverviewwidget' => '/HudsonOverviewWidget.class.php',
            'hudsonplugin' => '/hudsonPlugin.class.php',
            'hudsonplugindescriptor' => '/hudsonPluginDescriptor.class.php',
            'hudsonplugininfo' => '/hudsonPluginInfo.class.php',
            'hudsontestresult' => '/HudsonTestResult.class.php',
            'hudsonviews' => '/hudsonViews.class.php',
            'hudsonwidget' => '/HudsonWidget.class.php',
            'pluginhudsonjobdao' => '/PluginHudsonJobDao.class.php',
            'svnpathsupdater' => '/SVNPathsUpdater.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload9c5aff42d030bfb55852230cdefb47ad');
// @codeCoverageIgnoreEnd
