<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoloadb3c6cd8c7a081d853d56cdc8ae14199c($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'pluginaction' => '/mvc/PluginAction.class.php',
            'plugincontroler' => '/mvc/PluginControler.class.php',
            'pluginview' => '/mvc/PluginView.class.php',
            'requesthelp' => '/RequestHelp.class.php',
            'requesthelpactions' => '/RequestHelpActions.class.php',
            'requesthelpdao' => '/RequestHelpDao.class.php',
            'requesthelpdbdriver' => '/RequestHelpDBDriver.class.php',
            'requesthelpplugin' => '/requesthelpPlugin.class.php',
            'requesthelpplugindescriptor' => '/RequestHelpPluginDescriptor.class.php',
            'requesthelpplugininfo' => '/RequestHelpPluginInfo.class.php',
            'requesthelpviews' => '/RequestHelpViews.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoloadb3c6cd8c7a081d853d56cdc8ae14199c');
// @codeCoverageIgnoreEnd