<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload1402acaf7cccc3609244552a26b80baa($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'tuleap\\velocity\\plugin\\plugindescriptor' => '/Velocity/Plugin/PluginDescriptor.php',
            'tuleap\\velocity\\plugin\\plugininfo' => '/Velocity/Plugin/PluginInfo.php',
            'tuleap\\velocity\\semantic\\semanticvelocity' => '/Velocity/Semantic/SemanticVelocity.php',
            'tuleap\\velocity\\semantic\\semanticvelocityadminpresenter' => '/Velocity/Semantic/SemanticVelocityAdminPresenter.php',
            'tuleap\\velocity\\semantic\\semanticvelocitydao' => '/Velocity/Semantic/SemanticVelocityDao.php',
            'tuleap\\velocity\\semantic\\semanticvelocitypresenter' => '/Velocity/Semantic/SemanticVelocityPresenter.php',
            'tuleap\\velocity\\velocitycalculator' => '/Velocity/VelocityCalculator.php',
            'tuleap\\velocity\\velocitycomputationchecker' => '/Velocity/VelocityComputationChecker.php',
            'tuleap\\velocity\\velocitydao' => '/Velocity/VelocityDao.php',
            'velocityplugin' => '/velocityPlugin.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload1402acaf7cccc3609244552a26b80baa');
// @codeCoverageIgnoreEnd
