<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload5bc86ff8fda650dcfc316e0f3b865463($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'tuleap\\velocity\\plugin\\plugindescriptor' => '/Velocity/Plugin/PluginDescriptor.php',
            'tuleap\\velocity\\plugin\\plugininfo' => '/Velocity/Plugin/PluginInfo.php',
            'tuleap\\velocity\\semantic\\semanticvelocity' => '/Velocity/Semantic/SemanticVelocity.php',
            'tuleap\\velocity\\semantic\\semanticvelocityadminpresenter' => '/Velocity/Semantic/SemanticVelocityAdminPresenter.php',
            'tuleap\\velocity\\semantic\\semanticvelocitydao' => '/Velocity/Semantic/SemanticVelocityDao.php',
            'tuleap\\velocity\\semantic\\semanticvelocitypresenter' => '/Velocity/Semantic/SemanticVelocityPresenter.php',
            'velocityplugin' => '/velocityPlugin.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload5bc86ff8fda650dcfc316e0f3b865463');
// @codeCoverageIgnoreEnd
