truncate plugin_docman_item;
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (2, 0, 'Architecture', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (3, 0, 'Delivery', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (4, 2, 'Docman', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (5, 3, 'Codex 2.4', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (6, 3, 'Codex 2.6', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (7, 2, 'Wiki', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (8, 7, 'Attachements', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (9, 8, 'Images', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (10, 9, 'Jpeg', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (11, 9, 'Png', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (12, 9, 'Gif', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (13, 8, 'Graphs', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (14, 7, 'Wysywyg', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (15, 2, 'Authentication', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (16, 15, 'Ldap', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (17, 16, 'Users', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (18, 16, 'Groups', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (19, 15, 'Database', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (20, 19, 'Codex', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (21, 23, 'Folder', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (22, 4, 'Metadata', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (23, 4, 'Item', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (24, 23, 'Document', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (25, 4, 'Workflow', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (26, 5, 'User Documentation', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (27, 5, 'Programmer Guide', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (28, 5, 'Installation Guide', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (29, 5, 'Administration Guide', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (30, 26, 'BecomingACodeXCitizen', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (31, 26, 'BookInfo', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (32, 26, 'BugTrackingSystem', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (33, 26, 'CodeXSiteOverview', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (34, 26, 'CodeX_User_Guide', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (35, 26, 'CommunicationServices', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (36, 26, 'CreatingANewProject', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (37, 26, 'DocumentManager', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (38, 26, 'FileRelease', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (39, 26, 'Introduction', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (40, 26, 'OtherServices', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (41, 26, 'ParametersDefault', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (42, 26, 'ParametersLocal', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (43, 26, 'PatchManager', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (44, 26, 'ProjectAdministration', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (45, 26, 'ProjectSummary', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (46, 26, 'ProjectWebSite', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (47, 26, 'References', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (48, 26, 'SupportRequestManager', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (49, 26, 'SurveyManager', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (50, 26, 'TaskManager', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (51, 26, 'Tracker', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (52, 26, 'VersionControlWithCVS', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (53, 26, 'VersionControlWithSubversion', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (54, 26, 'Wiki', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (55, 6, 'User Documentation', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (56, 6, 'Programmer Guide', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (57, 6, 'Installation Guide', 101, 1);
INSERT INTO plugin_docman_item(item_id, parent_id, title, group_id, item_type) VALUES (58, 6, 'Administration Guide', 101, 1);