<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload052d0bfa99c411adfe57d841a8527a13($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'pluginsadministration' => '/PluginsAdministration.class.php',
            'pluginsadministration_manageallowedprojectspresenter' => '/ManageAllowedProjectsPresenter.class.php',
            'pluginsadministration_presenter_installedpluginspresenter' => '/Presenter/installedPluginsPresenter.class.php',
            'pluginsadministrationactions' => '/PluginsAdministrationActions.class.php',
            'pluginsadministrationplugin' => '/pluginsadministrationPlugin.class.php',
            'pluginsadministrationplugindescriptor' => '/PluginsAdministrationPluginDescriptor.class.php',
            'pluginsadministrationplugininfo' => '/PluginsAdministrationPluginInfo.class.php',
            'pluginsadministrationviews' => '/PluginsAdministrationViews.class.php',
            'tuleap\\pluginsadministration\\availablepluginspresenter' => '/AvailablePluginsPresenter.php',
            'tuleap\\pluginsadministration\\plugindisablerverifier' => '/PluginDisablerVerifier.php',
            'tuleap\\pluginsadministration\\pluginpropertiespresenter' => '/PluginPropertiesPresenter.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload052d0bfa99c411adfe57d841a8527a13');
// @codeCoverageIgnoreEnd
