<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload985736ee83d56cb8b0ba441f61f21cee($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'pluginsadministration' => '/PluginsAdministration.class.php',
            'pluginsadministration_manageallowedprojectspresenter' => '/ManageAllowedProjectsPresenter.class.php',
            'pluginsadministration_presenter_installedpluginspresenter' => '/Presenter/installedPluginsPresenter.class.php',
            'pluginsadministrationactions' => '/PluginsAdministrationActions.class.php',
            'pluginsadministrationplugin' => '/pluginsadministrationPlugin.class.php',
            'pluginsadministrationplugindescriptor' => '/PluginsAdministrationPluginDescriptor.class.php',
            'pluginsadministrationplugininfo' => '/PluginsAdministrationPluginInfo.class.php',
            'pluginsadministrationviews' => '/PluginsAdministrationViews.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload985736ee83d56cb8b0ba441f61f21cee');
// @codeCoverageIgnoreEnd
