<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:src="http://nwalsh.com/xmlns/litprog/fragment" exclude-result-prefixes="src" version="1.0">

<!-- This file is generated from param.xweb; do not edit this file! -->

<!--
//
// CodeX: Breaking Down the Barriers to Source Code Sharing inside Xerox
// Copyright (c) Xerox Corporation, CodeX / CodeX Team, 2001-2002. All Rights Reserved
// http://codex.xerox.com
//
// $Id: 
//
//	Originally written by Stephane Bouhet 2002, CodeX Team, Xerox
//
-->

<!-- CX-SBT: Default font : Helvetica, 11 -->
<xsl:param name="body.font.family">Helvetica</xsl:param>
<xsl:param name="body.font.master">11</xsl:param>

<!-- CX-SBT: auto numerotation -->
<xsl:param name="section.autolabel" select="1"/>
<xsl:param name="section.label.includes.component.label" select="1"/>

<!-- CX-SBT: default alignment -->
<xsl:param name="alignment">left</xsl:param>

<!-- CX-SBT: Attribute for the tip, important, etc -->
<xsl:attribute-set name="admonition.title.properties">
  <xsl:attribute name="font-size">10pt</xsl:attribute>
  <xsl:attribute name="font-weight">bold</xsl:attribute>
  <xsl:attribute name="hyphenate">false</xsl:attribute>
  <xsl:attribute name="keep-with-next.within-column">always</xsl:attribute>
  <xsl:attribute name="text-align">center</xsl:attribute>
</xsl:attribute-set>

<!-- CX-SBT: The figure caption is after the figure itself -->
<xsl:param name="formal.title.placement">
figure after
example after
equation before
table after
procedure before
</xsl:param>

<!-- CX-SBT: Attribute of the formal title (figure, example and table title) -->
<xsl:attribute-set name="formal.title.properties" use-attribute-sets="normal.para.spacing">
  <xsl:attribute name="font-weight">bold</xsl:attribute>
  <xsl:attribute name="font-size">10pt</xsl:attribute>
  <xsl:attribute name="hyphenate">false</xsl:attribute>
  <xsl:attribute name="keep-with-next.within-column">always</xsl:attribute>
  <xsl:attribute name="space-after.minimum">0.4em</xsl:attribute>
  <xsl:attribute name="space-after.optimum">0.6em</xsl:attribute>
  <xsl:attribute name="space-after.maximum">0.8em</xsl:attribute>
  <xsl:attribute name="text-align">center</xsl:attribute>
</xsl:attribute-set>

<!-- CX-SBT: Don't show the link for the URL -->
<xsl:param name="ulink.show" select="0"/>

<!-- CX-SBT: For the link, use the underline decoration -->
<xsl:attribute-set name="ulink.properties">
  <xsl:attribute name="text-decoration">underline</xsl:attribute>
</xsl:attribute-set>

<!-- CX-SBT: For the copyright, generate a year range -->
<xsl:param name="make.year.ranges" select="1"/>

<!-- CX-SBT: For tip, important, etc, use the size font : 10pt -->
<xsl:attribute-set name="admonition.properties">
  <xsl:attribute name="font-size">8pt</xsl:attribute>
</xsl:attribute-set>

<!-- CX-SBT: Spacing for the itemizedList -->
<xsl:attribute-set name="list.block.spacing">
  <xsl:attribute name="space-before.optimum">0.1em</xsl:attribute>
  <xsl:attribute name="space-before.minimum">0.1em</xsl:attribute>
  <xsl:attribute name="space-before.maximum">0.1em</xsl:attribute>
  <xsl:attribute name="start-indent">2em</xsl:attribute>
</xsl:attribute-set>

<!-- CX-SBT: Spacing for the procedure/step (new attribute-set) -->
<xsl:attribute-set name="step.item.spacing">
  <xsl:attribute name="space-before.optimum">0em</xsl:attribute>
  <xsl:attribute name="space-before.minimum">0em</xsl:attribute>
  <xsl:attribute name="space-before.maximum">0.2em</xsl:attribute>
</xsl:attribute-set>

<!-- CX-SBT: Top margin -->
<xsl:param name="body.margin.top">0.8in</xsl:param>

<!-- CX-SBT: Attributes for the table and all its elements -->
<xsl:attribute-set name="table.properties">
  <xsl:attribute name="font-size">9pt</xsl:attribute>
  <xsl:attribute name="border-left-style">solid</xsl:attribute>
  <xsl:attribute name="border-right-width">0.5pt</xsl:attribute>
  <xsl:attribute name="border-top-width">0.5pt</xsl:attribute>
  <xsl:attribute name="border-bottom-width">0.5pt</xsl:attribute>
  <xsl:attribute name="border-right-style">solid</xsl:attribute>
  <xsl:attribute name="border-top-style">solid</xsl:attribute>
  <xsl:attribute name="border-bottom-style">solid</xsl:attribute>
  <xsl:attribute name="border-collapse">collapse</xsl:attribute>
  <xsl:attribute name="border-left-width">0.5pt</xsl:attribute>
  <xsl:attribute name="width">80%</xsl:attribute>
</xsl:attribute-set>

<!-- CX-SBT: Attributes for the table header -->
<xsl:attribute-set name="table.header">
  <xsl:attribute name="background-color">rgb(238, 238, 238)</xsl:attribute>
  <xsl:attribute name="font-weight">bold</xsl:attribute>
  <xsl:attribute name="text-align">left</xsl:attribute>
</xsl:attribute-set>

<!-- CX-SBT: Turns page numbers in xrefs on -->
<xsl:param name="insert.xref.page.number" select="1"/>

<!-- CX-SBT: For the programlisting tag -->
<xsl:attribute-set name="verbatim.properties">
  <xsl:attribute name="space-before.minimum">0em</xsl:attribute>
  <xsl:attribute name="space-before.optimum">0em</xsl:attribute>
  <xsl:attribute name="space-before.maximum">0em</xsl:attribute>
</xsl:attribute-set>

<!-- CX-SBT: For the programlisting tag -->
<xsl:attribute-set name="monospace.verbatim.properties" use-attribute-sets="verbatim.properties">
  <xsl:attribute name="font-family">
    <xsl:value-of select="$monospace.font.family"/>
  </xsl:attribute>
  <xsl:attribute name="font-size">
    <xsl:value-of select="$body.font.master"/>
    <xsl:text>pt</xsl:text>
  </xsl:attribute>
</xsl:attribute-set>

<!-- CX-SBT: No toc of table, example, equation -->
<xsl:param name="generate.toc">
/appendix toc
/article  toc
book      toc,figure
/chapter  toc
part      toc
/preface  toc
qandadiv  toc
qandaset  toc
reference toc
/section  toc
set       toc
</xsl:param>

<!-- CX-SBT: No watermark image -->
<xsl:param name="draft.watermark.image" select="''"/>

</xsl:stylesheet>
