<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload6444b3220e4c721c254847ed3c7a5dbe($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'artifactsfoldersplugin' => '/artifactsfoldersPlugin.class.php',
            'tuleap\\artifactsfolders\\artifactsfoldersplugindescriptor' => '/ArtifactsFoldersPluginDescriptor.php',
            'tuleap\\artifactsfolders\\artifactsfoldersplugininfo' => '/ArtifactsFoldersPluginInfo.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload6444b3220e4c721c254847ed3c7a5dbe');
// @codeCoverageIgnoreEnd
