<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload7a3c8844ecb09369e1e50ef909fdab41($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'artifactsfoldersplugin' => '/artifactsfoldersPlugin.class.php',
            'tuleap\\artifactsfolders\\artifactsfoldersplugindescriptor' => '/ArtifactsFoldersPluginDescriptor.php',
            'tuleap\\artifactsfolders\\artifactsfoldersplugininfo' => '/ArtifactsFoldersPluginInfo.php',
            'tuleap\\artifactsfolders\\folder\\artifactpresenter' => '/Folder/ArtifactPresenter.php',
            'tuleap\\artifactsfolders\\folder\\artifactpresenterbuilder' => '/Folder/ArtifactPresenterBuilder.php',
            'tuleap\\artifactsfolders\\folder\\artifactview' => '/Folder/ArtifactView.php',
            'tuleap\\artifactsfolders\\folder\\controller' => '/Folder/Controller.php',
            'tuleap\\artifactsfolders\\folder\\dao' => '/Folder/Dao.php',
            'tuleap\\artifactsfolders\\folder\\folderusageretriever' => '/Folder/FolderUsageRetriever.php',
            'tuleap\\artifactsfolders\\folder\\presenter' => '/Folder/Presenter.php',
            'tuleap\\artifactsfolders\\folder\\router' => '/Folder/Router.php',
            'tuleap\\artifactsfolders\\nature\\natureinfolderpresenter' => '/Nature/NatureInFolderPresenter.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload7a3c8844ecb09369e1e50ef909fdab41');
// @codeCoverageIgnoreEnd
