<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoloadeca5777f5adf118c4355df3488811055($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'tuleap\\theme\\burningparrot\\burningparrottheme' => '/BurningParrotTheme.php',
            'tuleap\\theme\\burningparrot\\footerpresenter' => '/FooterPresenter.php',
            'tuleap\\theme\\burningparrot\\headerpresenter' => '/HeaderPresenter.php',
            'tuleap\\theme\\burningparrot\\headerpresenterbuilder' => '/HeaderPresenterBuilder.php',
            'tuleap\\theme\\burningparrot\\javascriptpresenter' => '/JavascriptPresenter.php',
            'tuleap\\theme\\burningparrot\\navbar\\globalmenuitempresenter' => '/Navbar/GlobalMenuItemPresenter.php',
            'tuleap\\theme\\burningparrot\\navbar\\globalnavpresenter' => '/Navbar/GlobalNavPresenter.php',
            'tuleap\\theme\\burningparrot\\navbar\\presenter' => '/Navbar/Presenter.php',
            'tuleap\\theme\\burningparrot\\navbar\\presenterbuilder' => '/Navbar/PresenterBuilder.php',
            'tuleap\\theme\\burningparrot\\navbar\\searchpresenter' => '/Navbar/SearchPresenter.php',
            'tuleap\\theme\\burningparrot\\navbar\\usernavpresenter' => '/Navbar/UserNavPresenter.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoloadeca5777f5adf118c4355df3488811055');
// @codeCoverageIgnoreEnd
