<?xml version="1.0" encoding="utf-8"?>

<!-- This file is generated from param.xweb; do not edit this file! -->

<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:src="http://nwalsh.com/xmlns/litprog/fragment" exclude-result-prefixes="src" version="1.0">

<!--
//
// CodeX: Breaking Down the Barriers to Source Code Sharing inside Xerox
// Copyright (c) Xerox Corporation, CodeX / CodeX Team, 2001-2002. All Rights Reserved
// http://codex.xerox.com
//
// $Id: 
//
//	Originally written by Stephane Bouhet 2002, CodeX Team, Xerox
//
-->


<!-- CX-SBT: The figure captions are after the figures -->
<xsl:param name="formal.title.placement">
figure after
example after
equation before
table after
procedure before
</xsl:param>

<!-- CX-SBT: Name of the single HTML file, without the .html extension -->
<xsl:param name="root.filename" select="'CodeX_CLI'"></xsl:param>

<!-- CX-SBT: Generate the legal notice in the same file -->
<xsl:param name="generate.legalnotice.link" select="0"/>

<!-- CX-SBT: Generate the revision history in the same file   ### Doesn't work ! ### -->
<xsl:param name="generate.revhistory.link" select="0"></xsl:param>

<!-- CX-SBT: auto numerotation -->
<xsl:param name="section.autolabel" select="1"/>
<xsl:param name="section.label.includes.component.label" select="1"/>

<!-- CX-SBT: For tip, important, note, we increase the margins -->
<xsl:param name="admon.style">
  <xsl:text>margin-left: 1.5in; margin-right: 1.5in;</xsl:text>
</xsl:param>

<!-- CX-SBT: No toc of table, example, equation -->
<xsl:param name="generate.toc">
appendix  toc
article   toc
book      toc,figure
chapter   toc
part      toc
preface   toc
qandadiv  toc
qandaset  toc
reference toc
section   toc
set       toc
</xsl:param>

<!-- CX-SBT: Generate navigation bar -->
<xsl:param name="suppress.navigation" select="0"/>

<!-- CX-SBT: Use the id for the filename -->
<xsl:param name="use.id.as.filename" select="1"/>

</xsl:stylesheet>
