<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload7f8d34d88a5b12bb87a954208ce644d5($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'frsplugin' => '/frsPlugin.class.php',
            'tuleap\\frs\\additionalinformationpresenter' => '/AdditionalInformationPresenter.php',
            'tuleap\\frs\\link\\dao' => '/Link/Dao.php',
            'tuleap\\frs\\link\\retriever' => '/Link/Retriever.php',
            'tuleap\\frs\\link\\updater' => '/Link/Updater.php',
            'tuleap\\frs\\plugindescriptor' => '/FRS/PluginDescriptor.php',
            'tuleap\\frs\\plugininfo' => '/FRS/PluginInfo.php',
            'tuleap\\frs\\releasepresenter' => '/FRS/ReleasePresenter.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload7f8d34d88a5b12bb87a954208ce644d5');
// @codeCoverageIgnoreEnd
