<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload666f5a66213ac42f78a632dfc5155a64($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'frsplugin' => '/frsPlugin.class.php',
            'tuleap\\frs\\additionalinformationpresenter' => '/AdditionalInformationPresenter.php',
            'tuleap\\frs\\agiledashboardpaneinfo' => '/FRS/AgileDashboardPaneInfo.php',
            'tuleap\\frs\\artifactview' => '/FRS/ArtifactView.php',
            'tuleap\\frs\\link\\dao' => '/Link/Dao.php',
            'tuleap\\frs\\link\\retriever' => '/Link/Retriever.php',
            'tuleap\\frs\\link\\updater' => '/Link/Updater.php',
            'tuleap\\frs\\plugindescriptor' => '/FRS/PluginDescriptor.php',
            'tuleap\\frs\\plugininfo' => '/FRS/PluginInfo.php',
            'tuleap\\frs\\releasepresenter' => '/FRS/ReleasePresenter.php',
            'tuleap\\frs\\rest\\resourcesinjector' => '/FRS/REST/ResourcesInjector.php',
            'tuleap\\frs\\rest\\v1\\filerepresentation' => '/FRS/REST/v1/FileRepresentation.php',
            'tuleap\\frs\\rest\\v1\\packageminimalrepresentation' => '/FRS/REST/v1/PackageMinimalRepresentation.php',
            'tuleap\\frs\\rest\\v1\\packageminimalrepresentationpaginatedcollection' => '/FRS/REST/v1/PackageMinimalRepresentationPaginatedCollection.php',
            'tuleap\\frs\\rest\\v1\\packagerepresentation' => '/FRS/REST/v1/PackageRepresentation.php',
            'tuleap\\frs\\rest\\v1\\packageresource' => '/FRS/REST/v1/PackageResource.php',
            'tuleap\\frs\\rest\\v1\\projectresource' => '/FRS/REST/v1/ProjectResource.php',
            'tuleap\\frs\\rest\\v1\\releaserepresentation' => '/FRS/REST/v1/ReleaseRepresentation.php',
            'tuleap\\frs\\rest\\v1\\releaserepresentationpaginatedcollectionrepresentation' => '/FRS/REST/v1/ReleaseRepresentationPaginatedCollectionRepresentation.php',
            'tuleap\\frs\\rest\\v1\\releaseresource' => '/FRS/REST/v1/ReleaseResource.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload666f5a66213ac42f78a632dfc5155a64');
// @codeCoverageIgnoreEnd
