<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload1fcaaff24cfa2ed4c879f7879689215b($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'frsplugin' => '/frsPlugin.class.php',
            'tuleap\\frs\\plugindescriptor' => '/FRS/PluginDescriptor.php',
            'tuleap\\frs\\plugininfo' => '/FRS/PluginInfo.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload1fcaaff24cfa2ed4c879f7879689215b');
// @codeCoverageIgnoreEnd
