# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  "npm-^6" = nodeEnv.buildNodePackage {
    name = "npm";
    packageName = "npm";
    version = "6.14.13";
    src = fetchurl {
      url = "https://registry.npmjs.org/npm/-/npm-6.14.13.tgz";
      sha512 = "SRl4jJi0EBHY2xKuu98FLRMo3VhYQSA6otyLnjSEiHoSG/9shXCFNJy9tivpUJvtkN9s6VDdItHa5Rn+fNBzag==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "a package manager for JavaScript";
      homepage = "https://docs.npmjs.com/";
      license = "Artistic-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
