#!/bin/bash

# Copyright (c) STMicroelectronics, 2005. All Rights Reserved.
#
# Originally written by Manuel Vacelet, 2005
#
# This file is a part of CodeX.
#
# CodeX is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# CodeX is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CodeX; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# $Id$

set -e

# Default tools
GREP="/bin/grep"
SED="/bin/sed"

# Common functions
error() {
    echo "Error $@"
    exit 1
}

# Scripts variables
PHP=""
PHP_INI=""

# Check if CODEX_LOCAL_INC variable exists in the environement
# or set a default value
if [ ! -f "${CODEX_LOCAL_INC}" ]; then
    CODEX_LOCAL_INC="/etc/codex/conf/local.inc"
fi
if [ ! -f "${CODEX_LOCAL_INC}" ]; then
    error "No valid CODEX_LOCAL_INC found. Please update your environnement."
fi

# Parse local.inc file
PHP=$(${GREP} '^\$php_cmd' ${CODEX_LOCAL_INC} | ${SED} -e 's/\$php_cmd\s*=\s*\(.*\);\(.*\)/\1/' | tr -d '"' | tr -d "'")
PHP_INI=$(${GREP} '^\$php_ini' ${CODEX_LOCAL_INC} | ${SED} -e 's/\$php_ini\s*=\s*\(.*\);\(.*\)/\1/' | tr -d '"' | tr -d "'")

# Check parsed values
if [ ! -x "${PHP}" ]; then
    error "No valid php intepreter found. Please update your local.inc"
fi
if [ ! -f "${PHP_INI}" ]; then
    error "No valid php.ini file found. Please update your local.inc"
fi

# Finaly runs php interpretor
export CODEX_LOCAL_INC
exec "${PHP}" -c "${PHP_INI}" $@
