#!/bin/bash

if [ -d '/usr/share/tuleap' ]; then
    DISPLAY_ERRORS=true /usr/share/tuleap/src/utils/php-launcher.sh /usr/share/tuleap/src/utils/tuleap.php $@
else
    DISPLAY_ERRORS=true /usr/share/codendi/src/utils/php-launcher.sh /usr/share/codendi/src/utils/tuleap.php $@
fi