<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload1930314c90ad4827a20b1e2f379178db($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'rest_testdatabuilder' => '/TestDataBuilder.php',
            'restbase' => '/RestBase.php',
            'test\\rest\\cache' => '/Cache.php',
            'test\\rest\\requestwrapper' => '/RequestWrapper.php',
            'test\\rest\\tracker\\tracker' => '/tracker/Tracker.php',
            'test\\rest\\tracker\\trackerfactory' => '/tracker/TrackerFactory.php',
            'test\\rest\\tuleapconfig' => '/TuleapConfig.php',
            'tuleap\\rest\\artifactbase' => '/ArtifactBase.php',
            'tuleap\\rest\\artifactfilebase' => '/ArtifactFileBase.php',
            'tuleap\\rest\\cardsbase' => '/CardsBase.php',
            'tuleap\\rest\\milestonebase' => '/MilestoneBase.php',
            'tuleap\\rest\\projectbase' => '/ProjectBase.php',
            'tuleap\\rest\\trackerbase' => '/TrackerBase.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload1930314c90ad4827a20b1e2f379178db');
// @codeCoverageIgnoreEnd
