<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload057892809dc31051a7131236f0809521($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'projectquotahtml' => '/ProjectQuotaHtml.class.php',
            'projectquotamanager' => '/ProjectQuotaManager.class.php',
            'projectsoverquotatableheaderpresenter' => '/ProjectsOverQuotaTableHeaderPresenter.class.php',
            'projectsoverquotatablepresenter' => '/ProjectsOverQuotaTablePresenter.class.php',
            'statistics_configurationdao' => '/Statistics_ConfigurationDao.class.php',
            'statistics_configurationmanager' => '/Statistics_ConfigurationManager.class.php',
            'statistics_diskusagedao' => '/Statistics_DiskUsageDao.class.php',
            'statistics_diskusagegraph' => '/Statistics_DiskUsageGraph.class.php',
            'statistics_diskusagehtml' => '/Statistics_DiskUsageHtml.class.php',
            'statistics_diskusagemanager' => '/Statistics_DiskUsageManager.class.php',
            'statistics_diskusageoutput' => '/Statistics_DiskUsageOutput.class.php',
            'statistics_diskusagepurger' => '/Statistics_DiskUsagePurger.class.php',
            'statistics_event' => '/Statistics_Event.php',
            'statistics_formatter' => '/Statistics_Formatter.class.php',
            'statistics_formatter_cvs' => '/Statistics_Formatter_Cvs.class.php',
            'statistics_formatter_scm' => '/Statistics_Formatter_Scm.class.php',
            'statistics_formatter_svn' => '/Statistics_Formatter_Svn.class.php',
            'statistics_projectquotadao' => '/Statistics_ProjectQuotaDao.class.php',
            'statistics_scmcvsdao' => '/Statistics_ScmCvsDao.class.php',
            'statistics_scmsvndao' => '/Statistics_ScmSvnDao.class.php',
            'statistics_services_usageformatter' => '/Statistics_Services_UsageFormatter.class.php',
            'statistics_servicesusagedao' => '/Statistics_ServicesUsageDao.class.php',
            'statistics_soapserver' => '/Statistics_SOAPServer.class.php',
            'statistics_widget_projectstatistics' => '/Statistics_Widget_ProjectStatistics.class.php',
            'statisticsaggregatordao' => '/StatisticsAggregatorDao.class.php',
            'statisticsplugin' => '/statisticsPlugin.class.php',
            'statisticsplugindescriptor' => '/StatisticsPluginDescriptor.class.php',
            'statisticsplugininfo' => '/StatisticsPluginInfo.class.php',
            'systemevent_statistics_daily' => '/SystemEvent_STATISTICS_DAILY.php',
            'systemeventqueuestatistics' => '/SystemEventQueueStatistics.php',
            'tuleap\\statistics\\frequenciespresenter' => '/FrequenciesPresenter.php',
            'tuleap\\statistics\\frequenciessearchfieldspresenter' => '/FrequenciesSearchFieldsPresenter.php',
            'tuleap\\statistics\\frequenciessearchfieldspresenterbuilder' => '/FrequenciesSearchFieldsPresenterBuilder.php',
            'tuleap\\statistics\\serviceusagepresenter' => '/ServiceUsagePresenter.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload057892809dc31051a7131236f0809521');
// @codeCoverageIgnoreEnd
