/**
 * CodeX: Breaking Down the Barriers to Source Code Sharing
 *
 * Copyright (c) Xerox Corporation, CodeX, 2007. All Rights Reserved
 *
 * This file is licensed under the CodeX Component Software License
 *
 * @author Anne Hardyau
 * @author Marc Nazarian
 */

package com.xerox.xrce.codex.jri.model;

import com.xerox.xrce.codex.jri.model.wsproxy.ArtifactCC;

/**
 * CxArtifactCC is the class for CC List of an artifact.
 * 
 */
public class CxArtifactCC extends CxFromServer {

    /**
     * The comment of this CC
     */
    private String comment;

    /**
     * The email or username of this CC
     */
    private String email;

    /**
     * The name of user who added this CC
     */
    private String addedByName;

    /**
     * The date this CC has been added (unix time stamp)
     */
    private int date;

    /**
     * The ID of this CC
     */
    private int id;

    /**
     * Constructor from an ArtifactCC Object (generated by WSDL2JAVA)
     * 
     * @param server the server this CC belongs to
     * @param artifactCC the ArtifactCC Object
     */
    public CxArtifactCC(CxServer server, ArtifactCC artifactCC) {
        super(server);
        this.comment = artifactCC.getComment();
        this.email = artifactCC.getEmail();
        this.addedByName = artifactCC.getAdded_by_name();
        this.date = artifactCC.getDate();
        this.id = artifactCC.getArtifact_cc_id();
    }

    /**
     * Constructor from data
     * 
     * @param server the server the CC belongs to
     * @param comment the comment of the CC
     * @param email the email or username of the CC
     */
    public CxArtifactCC(CxServer server, String comment, String email) {
        super(server);
        this.comment = comment;
        this.email = email;
        this.addedByName = "";
        this.date = 0;
    }

    /**
     * Returns the ID of this CC
     * 
     * @return the ID of this CC
     */
    public int getId() {
        return id;
    }

    /**
     * Returns the email (or username) of this CC
     * 
     * @return the email (or username) of this CC
     */
    public String getEmail() {
        return email;
    }

    /**
     * Returns the comment of this CC
     * 
     * @return the comment of this CC
     */
    public String getComment() {
        return comment;
    }

    /**
     * Returns the name of the user that added this CC
     * 
     * @return the name of the user that added this CC
     */
    public String getAddedByName() {
        return addedByName;
    }

    /**
     * Returns the date this CC has been added
     * 
     * @return the date this CC has been added
     */
    public int getDate() {
        return date;
    }

}
