<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoloade63995f9c4f5dfa9cc7d8f598fa8d299($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'bugzilla_referenceplugin' => '/bugzilla_referencePlugin.class.php',
            'tuleap\\bugzilla\\administration\\controller' => '/Bugzilla/Administration/Controller.php',
            'tuleap\\bugzilla\\administration\\presenter' => '/Bugzilla/Administration/Presenter.php',
            'tuleap\\bugzilla\\administration\\referencepresenter' => '/Bugzilla/Administration/ReferencePresenter.php',
            'tuleap\\bugzilla\\administration\\router' => '/Bugzilla/Administration/Router.php',
            'tuleap\\bugzilla\\plugin\\descriptor' => '/Bugzilla/Plugin/Descriptor.php',
            'tuleap\\bugzilla\\plugin\\info' => '/Bugzilla/Plugin/Info.php',
            'tuleap\\bugzilla\\reference\\dao' => '/Bugzilla/Reference/Dao.php',
            'tuleap\\bugzilla\\reference\\keywordisalreadyusedexception' => '/Bugzilla/Reference/KeywordIsAlreadyUsedException.php',
            'tuleap\\bugzilla\\reference\\keywordisinvalidexception' => '/Bugzilla/Reference/KeywordIsInvalidException.php',
            'tuleap\\bugzilla\\reference\\reference' => '/Bugzilla/Reference/Reference.php',
            'tuleap\\bugzilla\\reference\\referenceretriever' => '/Bugzilla/Reference/ReferenceRetriever.php',
            'tuleap\\bugzilla\\reference\\referencesaver' => '/Bugzilla/Reference/ReferenceSaver.php',
            'tuleap\\bugzilla\\reference\\requiredfieldemptyexception' => '/Bugzilla/Reference/RequiredFieldEmptyException.php',
            'tuleap\\bugzilla\\reference\\serverisinvalidexception' => '/Bugzilla/Reference/ServerIsInvalidException.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoloade63995f9c4f5dfa9cc7d8f598fa8d299');
// @codeCoverageIgnoreEnd
