
INSERT INTO service(group_id, label, description, short_name, link, is_active, is_used, scope, rank) VALUES ( 101 , 'plugin_docman:service_lbl_key' , 'plugin_docman:service_desc_key' , 'docman', '/plugins/docman/?group_id=101', 1 , 1 , 'system',  95 );

INSERT INTO plugin_docman_item(item_id, parent_id, group_id, title, description, create_date, update_date, user_id, rank, item_type, link_url, wiki_page, file_is_embedded) VALUES (1, 0, 101, 'ProjetDeTest', 'Les documents de ProjetDeTest', 0, 0, 101, NULL, 1, NULL, NULL, NULL);
INSERT INTO plugin_docman_item(item_id, parent_id, group_id, title, description, create_date, update_date, user_id, rank, item_type, link_url, wiki_page, file_is_embedded) VALUES (2, 1, 101, 'Folder_A', '', 1147431916, 1147431916, 101, 0, 1, NULL, NULL, NULL);
INSERT INTO plugin_docman_item(item_id, parent_id, group_id, title, description, create_date, update_date, user_id, rank, item_type, link_url, wiki_page, file_is_embedded) VALUES (3, 1, 101, 'Folder_B', '', 1147431933, 1147431933, 101, 0, 1, NULL, NULL, NULL);
INSERT INTO plugin_docman_item(item_id, parent_id, group_id, title, description, create_date, update_date, user_id, rank, item_type, link_url, wiki_page, file_is_embedded) VALUES (4, 1, 101, 'Folder_C', '', 1147431950, 1147431950, 101, 0, 1, NULL, NULL, NULL);
INSERT INTO plugin_docman_item(item_id, parent_id, group_id, title, description, create_date, update_date, user_id, rank, item_type, link_url, wiki_page, file_is_embedded) VALUES (5, 1, 101, 'Folder_D', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin leo. Maecenas viverra lorem sed tellus. Proin et ligula. Pellentesque ac arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce tincidunt lacinia justo. Praesent sit amet purus sit amet ante laoreet vestibulum. Integer at arcu. Donec sapien ligula, interdum quis, imperdiet sit amet, convallis quis, massa. Aliquam a diam non nisl viverra viverra. Integer eget velit. Fusce aliquam, ligula eu accumsan lobortis, odio diam rutrum lectus, in hendrerit dui risus id mauris. Suspendisse posuere tellus ultricies justo.', 1147432016, 1147432207, 101, 0, 1, NULL, NULL, NULL);
INSERT INTO plugin_docman_item(item_id, parent_id, group_id, title, description, create_date, update_date, user_id, rank, item_type, link_url, wiki_page, file_is_embedded) VALUES (6, 1, 101, 'Folder_E', '', 1147432031, 1147432031, 101, 0, 1, NULL, NULL, NULL);
INSERT INTO plugin_docman_item(item_id, parent_id, group_id, title, description, create_date, update_date, user_id, rank, item_type, link_url, wiki_page, file_is_embedded) VALUES (7, 2, 101, 'Folder_AA', '', 1147432091, 1147432091, 101, 0, 1, NULL, NULL, NULL);
INSERT INTO plugin_docman_item(item_id, parent_id, group_id, title, description, create_date, update_date, user_id, rank, item_type, link_url, wiki_page, file_is_embedded) VALUES (8, 2, 101, 'Folder_AB', '', 1147432113, 1147432113, 101, 0, 1, NULL, NULL, NULL);
INSERT INTO plugin_docman_item(item_id, parent_id, group_id, title, description, create_date, update_date, user_id, rank, item_type, link_url, wiki_page, file_is_embedded) VALUES (9, 3, 101, 'Folder_BA', '', 1147432137, 1147432137, 101, 0, 1, NULL, NULL, NULL);
INSERT INTO plugin_docman_item(item_id, parent_id, group_id, title, description, create_date, update_date, user_id, rank, item_type, link_url, wiki_page, file_is_embedded) VALUES (10, 3, 101, 'Folder_BB', '', 1147432155, 1147432155, 101, 0, 1, NULL, NULL, NULL);
INSERT INTO plugin_docman_item(item_id, parent_id, group_id, title, description, create_date, update_date, user_id, rank, item_type, link_url, wiki_page, file_is_embedded) VALUES (11, 4, 101, 'Folder_CA', '', 1147432231, 1147432231, 101, 0, 1, NULL, NULL, NULL);
INSERT INTO plugin_docman_item(item_id, parent_id, group_id, title, description, create_date, update_date, user_id, rank, item_type, link_url, wiki_page, file_is_embedded) VALUES (12, 4, 101, 'Folder_CB', '', 1147432252, 1147432252, 101, 0, 1, NULL, NULL, NULL);
INSERT INTO plugin_docman_item(item_id, parent_id, group_id, title, description, create_date, update_date, user_id, rank, item_type, link_url, wiki_page, file_is_embedded) VALUES (13, 4, 101, 'Folder_CC', '', 1147432269, 1147432269, 101, 0, 1, NULL, NULL, NULL);
INSERT INTO plugin_docman_item(item_id, parent_id, group_id, title, description, create_date, update_date, user_id, rank, item_type, link_url, wiki_page, file_is_embedded) VALUES (14, 13, 101, 'Link_A', '', 1147432326, 1147432326, 101, 0, 3, 'http://www.google.fr', '', NULL);
INSERT INTO plugin_docman_item(item_id, parent_id, group_id, title, description, create_date, update_date, user_id, rank, item_type, link_url, wiki_page, file_is_embedded) VALUES (15, 11, 101, 'Wiki_A', '', 1147432577, 1147432577, 101, 0, 5, '', 'wiki', NULL);
INSERT INTO plugin_docman_item(item_id, parent_id, group_id, title, description, create_date, update_date, user_id, rank, item_type, link_url, wiki_page, file_is_embedded) VALUES (16, 11, 101, 'Wiki_B', '', 1147432614, 1147432614, 101, 0, 5, '', 'wiki', NULL);
INSERT INTO plugin_docman_item(item_id, parent_id, group_id, title, description, create_date, update_date, user_id, rank, item_type, link_url, wiki_page, file_is_embedded) VALUES (17, 10, 101, 'Folder_BBA', '', 1147440045, 1147440045, 101, 0, 1, NULL, NULL, NULL);
INSERT INTO plugin_docman_item(item_id, parent_id, group_id, title, description, create_date, update_date, user_id, rank, item_type, link_url, wiki_page, file_is_embedded) VALUES (18, 3, 101, 'Link_B', '', 1147440078, 1147440078, 101, 0, 3, 'http://www.google.fr', '', NULL);

INSERT INTO plugin_docman_project_settings(group_id, view) VALUES (101, 'Icons');

INSERT INTO user_preferences (user_id, preference_name, preference_value) VALUES (101, 'plugin_docman_hide_101_4', '2');

INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_ADMIN', 101, 4);

INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_MANAGE', '2', 4);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_WRITE', '2', 3);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_READ', '2', 1);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_MANAGE', '1', 4);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_WRITE', '1', 3);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_READ', '1', 1);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_MANAGE', '3', 4);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_WRITE', '3', 3);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_READ', '3', 1);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_MANAGE', '4', 4);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_WRITE', '4', 3);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_READ', '4', 1);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_MANAGE', '5', 4);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_WRITE', '5', 3);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_READ', '5', 1);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_MANAGE', '6', 4);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_WRITE', '6', 3);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_READ', '6', 1);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_MANAGE', '7', 4);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_WRITE', '7', 3);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_READ', '7', 1);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_MANAGE', '8', 4);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_WRITE', '8', 3);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_READ', '8', 1);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_MANAGE', '9', 4);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_WRITE', '9', 3);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_READ', '9', 1);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_MANAGE', '10', 4);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_WRITE', '10', 3);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_READ', '10', 1);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_MANAGE', '11', 4);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_WRITE', '11', 3);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_READ', '11', 1);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_MANAGE', '12', 4);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_WRITE', '12', 3);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_READ', '12', 1);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_MANAGE', '13', 4);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_WRITE', '13', 3);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_READ', '13', 1);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_MANAGE', '14', 4);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_WRITE', '14', 3);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_READ', '14', 1);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_MANAGE', '15', 4);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_WRITE', '15', 3);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_READ', '15', 1);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_MANAGE', '16', 4);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_WRITE', '16', 3);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_READ', '16', 1);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_MANAGE', '17', 4);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_WRITE', '17', 3);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_READ', '17', 1);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_MANAGE', '18', 4);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_WRITE', '18', 3);
INSERT INTO permissions (permission_type, object_id, ugroup_id) VALUES ('PLUGIN_DOCMAN_READ', '18', 1);

