<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload51a236064b36252f017c3d4128e0c167($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'testing_campaign_campaigncontroller' => '/Campaign/CampaignController.class.php',
            'testing_requirement_requirementcontroller' => '/Requirement/RequirementController.class.php',
            'testing_testexecution_testexecutioncontroller' => '/TestExecution/TestExecutionController.class.php',
            'testingplugin' => '/testingPlugin.class.php',
            'testingplugindescriptor' => '/TestingPluginDescriptor.class.php',
            'testingplugininfo' => '/TestingPluginInfo.class.php',
            'testingrouter' => '/TestingRouter.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload51a236064b36252f017c3d4128e0c167');
// @codeCoverageIgnoreEnd