<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload6f3fe9d3a8397b4f222d5b78637ac00e($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'timetrackingplugin' => '/timetrackingPlugin.class.php',
            'tuleap\\timetracking\\admin\\admincontroller' => '/Timetracking/Admin/AdminController.php',
            'tuleap\\timetracking\\admin\\admindao' => '/Timetracking/Admin/AdminDao.php',
            'tuleap\\timetracking\\admin\\adminpresenter' => '/Timetracking/Admin/AdminPresenter.php',
            'tuleap\\timetracking\\admin\\timetrackingenabler' => '/Timetracking/Admin/TimetrackingEnabler.php',
            'tuleap\\timetracking\\admin\\timetrackingugroupdao' => '/Timetracking/Admin/TimetrackingUgroupDao.php',
            'tuleap\\timetracking\\admin\\timetrackingugroupretriever' => '/Timetracking/Admin/TimetrackingUgroupRetriever.php',
            'tuleap\\timetracking\\admin\\timetrackingugroupsaver' => '/Timetracking/Admin/TimetrackingUgroupSaver.php',
            'tuleap\\timetracking\\artifactview\\artifactview' => '/Timetracking/ArtifactView/ArtifactView.php',
            'tuleap\\timetracking\\artifactview\\artifactviewbuilder' => '/Timetracking/ArtifactView/ArtifactViewBuilder.php',
            'tuleap\\timetracking\\artifactview\\artifactviewpresenter' => '/Timetracking/ArtifactView/ArtifactViewPresenter.php',
            'tuleap\\timetracking\\permissions\\permissionsretriever' => '/Timetracking/Permissions/PermissionsRetriever.php',
            'tuleap\\timetracking\\rest\\resourcesinjector' => '/Timetracking/REST/ResourcesInjector.php',
            'tuleap\\timetracking\\rest\\v1\\minimalartifactrepresentation' => '/Timetracking/REST/v1/MinimalArtifactRepresentation.php',
            'tuleap\\timetracking\\rest\\v1\\timetrackingrepresentation' => '/Timetracking/REST/v1/TimetrackingRepresentation.php',
            'tuleap\\timetracking\\rest\\v1\\timetrackingrepresentationbuilder' => '/Timetracking/REST/v1/TimetrackingRepresentationBuilder.php',
            'tuleap\\timetracking\\rest\\v1\\timetrackingresource' => '/Timetracking/REST/v1/TimetrackingResource.php',
            'tuleap\\timetracking\\router' => '/Timetracking/Router.php',
            'tuleap\\timetracking\\time\\dateformatter' => '/Timetracking/Time/DateFormatter.php',
            'tuleap\\timetracking\\time\\paginatedtimes' => '/Timetracking/Time/PaginatedTimes.php',
            'tuleap\\timetracking\\time\\time' => '/Timetracking/Time/Time.php',
            'tuleap\\timetracking\\time\\timechecker' => '/Timetracking/Time/TimeChecker.php',
            'tuleap\\timetracking\\time\\timecontroller' => '/Timetracking/Time/TimeController.php',
            'tuleap\\timetracking\\time\\timedao' => '/Timetracking/Time/TimeDao.php',
            'tuleap\\timetracking\\time\\timepresenterbuilder' => '/Timetracking/Time/TimePresenterBuilder.php',
            'tuleap\\timetracking\\time\\timeretriever' => '/Timetracking/Time/TimeRetriever.php',
            'tuleap\\timetracking\\time\\timeupdater' => '/Timetracking/Time/TimeUpdater.php',
            'tuleap\\timetracking\\timetrackingexistingdateexception' => '/Timetracking/Exceptions/TimeTrackingExistingDateException.php',
            'tuleap\\timetracking\\timetrackingmissingtimeexception' => '/Timetracking/Exceptions/TimeTrackingMissingTimeException.php',
            'tuleap\\timetracking\\timetrackingnotallowedtoaddexception' => '/Timetracking/Exceptions/TimeTrackingNotAllowedToAddException.php',
            'tuleap\\timetracking\\timetrackingnotallowedtodeleteexception' => '/Timetracking/Exceptions/TimeTrackingNotAllowedToDeleteException.php',
            'tuleap\\timetracking\\timetrackingnotallowedtoeditexception' => '/Timetracking/Exceptions/TimeTrackingNotAllowedToEditException.php',
            'tuleap\\timetracking\\timetrackingnotbelongtouserexception' => '/Timetracking/Exceptions/TimeTrackingNotBelongToUserException.php',
            'tuleap\\timetracking\\timetrackingnotimeexception' => '/Timetracking/Exceptions/TimeTrackingNoTimeException.php',
            'tuleap\\timetracking\\timetrackingplugindescriptor' => '/TimetrackingPluginDescriptor.php',
            'tuleap\\timetracking\\timetrackingplugininfo' => '/TimetrackingPluginInfo.php',
            'tuleap\\timetracking\\widget\\userwidget' => '/Timetracking/Widget/UserWidget.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload6f3fe9d3a8397b4f222d5b78637ac00e');
// @codeCoverageIgnoreEnd
