<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoloadf6fca034fdf236f6762f7d3d2d44f7cf($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'chartdatabuilder' => '/data-transformation/ChartDataBuilder.class.php',
            'databuilder' => '/data-transformation/DataBuilder.class.php',
            'graphicenginehtml' => '/html-generators/GraphicEngineHtml.class.php',
            'graphicengineuserprefs' => '/common/GraphicEngineUserPrefs.class.php',
            'graphicreportfactory' => '/data-access/GraphicReportFactory.class.php',
            'graphontrackers_chart' => '/data-access/GraphOnTrackers_Chart.class.php',
            'graphontrackers_chart_bar' => '/data-access/GraphOnTrackers_Chart_Bar.class.php',
            'graphontrackers_chart_bardatabuilder' => '/data-transformation/GraphOnTrackers_Chart_BarDataBuilder.class.php',
            'graphontrackers_chart_gantt' => '/data-access/GraphOnTrackers_Chart_Gantt.class.php',
            'graphontrackers_chart_ganttdatabuilder' => '/data-transformation/GraphOnTrackers_Chart_GanttDataBuilder.class.php',
            'graphontrackers_chart_pie' => '/data-access/GraphOnTrackers_Chart_Pie.class.php',
            'graphontrackers_chart_piedatabuilder' => '/data-transformation/GraphOnTrackers_Chart_PieDataBuilder.class.php',
            'graphontrackers_chartdao' => '/data-access/GraphOnTrackers_ChartDao.class.php',
            'graphontrackers_engine' => '/graphic-library/GraphOnTrackers_Engine.class.php',
            'graphontrackers_engine_bar' => '/graphic-library/GraphOnTrackers_Engine_Bar.class.php',
            'graphontrackers_engine_gantt' => '/graphic-library/GraphOnTrackers_Engine_Gantt.class.php',
            'graphontrackers_engine_pie' => '/graphic-library/GraphOnTrackers_Engine_Pie.class.php',
            'graphontrackers_report' => '/data-access/GraphOnTrackers_Report.class.php',
            'graphontrackers_reportdao' => '/data-access/GraphOnTrackers_ReportDao.class.php',
            'graphontrackers_reportfactory' => '/data-access/GraphOnTrackers_ReportFactory.class.php',
            'graphontrackersplugin' => '/graphontrackersPlugin.class.php',
            'graphontrackersplugindescriptor' => '/GraphOnTrackersPluginDescriptor.class.php',
            'graphontrackersplugininfo' => '/GraphOnTrackersPluginInfo.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoloadf6fca034fdf236f6762f7d3d2d44f7cf');
// @codeCoverageIgnoreEnd