<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoloadf1be8e0f8ef885ae686a6145bb955408($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'referencealias_svnplugin' => '/referencealias_svnPlugin.class.php',
            'tuleap\\referencealiassvn\\dao' => '/ReferenceAliasSVN/Dao.php',
            'tuleap\\referencealiassvn\\plugin\\plugindescriptor' => '/ReferenceAliasSVN/Plugin/PluginDescriptor.php',
            'tuleap\\referencealiassvn\\plugin\\plugininfo' => '/ReferenceAliasSVN/Plugin/PluginInfo.php',
            'tuleap\\referencealiassvn\\referencesbuilder' => '/ReferenceAliasSVN/ReferencesBuilder.php',
            'tuleap\\referencealiassvn\\referencesimporter' => '/ReferenceAliasSVN/ReferencesImporter.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoloadf1be8e0f8ef885ae686a6145bb955408');
// @codeCoverageIgnoreEnd
