<?php
/**
 * Copyright (c) Enalean, 2013 - 2018. All Rights Reserved.
 *
 * This file is a part of Tuleap.
 *
 * Tuleap is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Tuleap is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Tuleap. If not, see <http://www.gnu.org/licenses/>.
 */

// Mediawiki
$master_path = "/var/lib/codendi/mediawiki/master" ;
$mwdata_path = "/var/lib/codendi/mediawiki";
$mw_dbtype = "mysql";
$projects_path = "/var/lib/codendi/mediawiki/projects";
$config_path = "/etc/codendi";
$src_path = "/usr/share/mediawiki-tuleap-123";
$mw_style_path = '/plugins/mediawiki/www/skins';
$enable_compatibility_view = false;
$extension_mleb_path = "/usr/share/mediawiki-mleb-tuleap";
?>
