<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload25a4a69f7375b86cb06d3745faa71da1($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'teamforge_compat_svnplugin' => '/teamforge_compat_svnPlugin.class.php',
            'tuleap\\teamforgecompatsvn\\plugin\\plugindescriptor' => '/TeamforgeCompatSVN/Plugin/PluginDescriptor.php',
            'tuleap\\teamforgecompatsvn\\plugin\\plugininfo' => '/TeamforgeCompatSVN/Plugin/PluginInfo.php',
            'tuleap\\teamforgecompatsvn\\referencesimporter' => '/TeamforgeCompatSVN/ReferencesImporter.php',
            'tuleap\\teamforgecompatsvn\\teamforgecompatdao' => '/TeamforgeCompatSVN/TeamforgeCompatDao.php',
            'tuleap\\teamforgecompatsvn\\teamforgereferencesbuilder' => '/TeamforgeCompatSVN/TeamforgeReferencesBuilder.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload25a4a69f7375b86cb06d3745faa71da1');
// @codeCoverageIgnoreEnd
