# declare binaries path
declare -r awk="/usr/bin/awk"
declare -r basename="/usr/bin/basename"
declare -r cat="/usr/bin/cat"
declare -r date="/usr/bin/date"
declare -r getenforce="/usr/sbin/getenforce"
declare -r getopt="/usr/bin/getopt"
declare -r grep="/usr/bin/grep"
declare -r gzip="/usr/bin/gzip"
declare -r head="/usr/bin/head"
declare -r ln="/usr/bin/ln"
declare -r mkdir="/bin/mkdir"
declare -r mv="/usr/bin/mv"
declare -r mysql="/opt/rh/rh-mysql57/root/usr/bin/mysql"
declare -r mysqladmin="/opt/rh/rh-mysql57/root/usr/bin/mysqladmin"
declare -r mysqldump="/opt/rh/rh-mysql57/root/usr/bin/mysqldump"
declare -r php="/opt/rh/rh-php56/root/usr/bin/php"
declare -r php_launcher="/usr/share/tuleap/src/utils/php-launcher.sh"
declare -r printf="/usr/bin/printf"
declare -r su="/bin/su"
declare -r systemctl="/usr/bin/systemctl"
declare -r tr="/usr/bin/tr"

declare -a cmd=("${awk}" "${basename}" "${cat}" "${date}" "${getenforce}"
                "${getopt}" "${grep}" "${gzip}" "${head}" "${ln}" "${mkdir}"
                "${mv}" "${mysql}" "${mysqladmin}" "${mysqldump}" "${php}"
                "${printf}" "${su}" "${systemctl}" "${tr}")

# declare files path
declare -r install_dir="/usr/share/tuleap"
declare -r password_file="/root/.tuleap_passwd"
declare -r rh_release="/etc/redhat-release"
declare -r script_name="$(${basename} ${0})"
declare -r sefile="/etc/selinux/config"
declare -r src_db_mysql="${install_dir}/src/db/mysql"
declare -r sql_structure="${src_db_mysql}/database_structure.sql"
declare -r sql_init="${src_db_mysql}/database_initvalues.sql"
declare -r tuleap_dir="/etc/tuleap"
declare -r tuleap_conf="${tuleap_dir}/conf"
declare -r tuleap_log="/var/log/tuleap/tuleap_setup.log"
declare -r urandom="/dev/urandom"

# declare options
declare -r db_name="tuleap"
declare -r my_opt="--batch --skip-column-names"
declare -r project_admin="tuleap"
declare -i mysql_port=3306

assumeyes="false"
db_exist="false"
mysql_user="root"
mysql_password="NULL"
new_db="true"
server_name="NULL"
