<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload7ab69de35169a969e37946b6cd81f079($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'tuleap\\userlog\\userlogbuilder' => '/UserLogBuilder.php',
            'tuleap\\userlog\\userlogpresenter' => '/UserLogPresenter.php',
            'userlogdao' => '/UserLogDao.class.php',
            'userlogmanager' => '/UserLogManager.class.php',
            'userlogplugin' => '/userlogPlugin.class.php',
            'userlogplugindescriptor' => '/UserLogPluginDescriptor.class.php',
            'userlogplugininfo' => '/UserLogPluginInfo.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload7ab69de35169a969e37946b6cd81f079');
// @codeCoverageIgnoreEnd
