<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload6f6fc56fb5fed4cb76480e1ee4ed7ea9($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'userlogdao' => '/UserLogDao.class.php',
            'userlogmanager' => '/UserLogManager.class.php',
            'userlogplugin' => '/userlogPlugin.class.php',
            'userlogplugindescriptor' => '/UserLogPluginDescriptor.class.php',
            'userlogplugininfo' => '/UserLogPluginInfo.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload6f6fc56fb5fed4cb76480e1ee4ed7ea9');
// @codeCoverageIgnoreEnd