<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload38e3828de6ec81e1e66ead0e2162ea37($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'tuleap\\userlog\\userlogbuilder' => '/UserLogBuilder.php',
            'tuleap\\userlog\\userlogexporter' => '/UserLogExporter.php',
            'tuleap\\userlog\\userlogpresenter' => '/UserLogPresenter.php',
            'tuleap\\userlog\\userlogrouter' => '/UserLogRouter.php',
            'userlogdao' => '/UserLogDao.class.php',
            'userlogmanager' => '/UserLogManager.class.php',
            'userlogplugin' => '/userlogPlugin.class.php',
            'userlogplugindescriptor' => '/UserLogPluginDescriptor.class.php',
            'userlogplugininfo' => '/UserLogPluginInfo.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload38e3828de6ec81e1e66ead0e2162ea37');
// @codeCoverageIgnoreEnd
