<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload8be6a9a2d4e081c8ab90ef889a1783a8($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'projectlinks_widget_homepagelinks' => '/ProjectLinks_Widget_HomePageLinks.class.php',
            'projectlinksdao' => '/ProjectLinksDao.class.php',
            'projectlinksplugin' => '/projectlinksPlugin.class.php',
            'projectlinksplugindescriptor' => '/ProjectLinksPluginDescriptor.class.php',
            'projectlinksplugininfo' => '/ProjectLinksPluginInfo.class.php',
            'tvalidation' => '/form_utils.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload8be6a9a2d4e081c8ab90ef889a1783a8');
// @codeCoverageIgnoreEnd