#!/bin/sh -eu
# -e: Exit immediately if a command exits with a non-zero status.
# -u: Treat unset variables as an error when substituting.
#
# Copyright (c) STMicroelectronics, 2011. All Rights Reserved.
#
# This file is a part of Tuleap.
#
# Tuleap is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Tuleap is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Tuleap; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

logGitPushes()
{
	# Tuleap specific: Git logging stuffs

	revtype=$(git cat-file -t "$newrev")
	tuleap_login=$(whoami)
	repo_location=$(cd $GIT_DIR; pwd)
	tuleap_repo_name=$(basename $repo_location | sed -e 's/\.git$//')
	tuleap_group_name=$(basename $(dirname $repo_location))

	nbcommits=0
	if expr "$oldrev" : '0*$' >/dev/null
	then
		revspec=$newrev
	else
		revspec=$oldrev..$newrev
	fi

	nbcommits=$(git rev-list $revspec | wc -l)

	su -l codendiadm -c "/usr/share/codendi/src/utils/php-launcher.sh /usr/share/codendi/plugins/git/hooks/gitLog.php --group_name=$tuleap_group_name --login=$tuleap_login --type=$revtype --repo_name=$tuleap_repo_name --commits_number=$nbcommits >/dev/null"

}

# --- Config
# Set GIT_DIR either from the working directory, or from the environment
# variable.
GIT_DIR=$(git rev-parse --git-dir 2>/dev/null)
if [ -z "$GIT_DIR" ]; then
	echo >&2 "fatal: post-receive-log: GIT_DIR not set"
	exit 1
fi

if [ -n $oldrev -a -n $newrev ]; then
	logGitPushes $newrev $oldrev
else
	echo >&2 "fatal: post-receive-log: Usage is post-receive-log oldrev newrev"
	exit 1
fi
