#!/bin/sh -eu
# -e: Exit immediately if a command exits with a non-zero status.
# -u: Treat unset variables as an error when substituting.
#
#Copyright (c) Enalean 2012. All rights reserved
#
#Tuleap is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 2 of the License, or
#(at your option) any later version.
#
#Tuleap is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with Tuleap. If not, see <http://www.gnu.org/licenses/>.
# 

extractRef()
{
	tuleap_login=$(whoami)
	repo_location=$(cd $GIT_DIR; pwd)
	tuleap_repo_name=$(basename $repo_location | sed -e 's/\.git$//')
	
	for rev in $(git rev-list $oldrev..$newrev)
	do
		text=$(git cat-file -p "$rev")
	    echo "$text" | php /usr/share/codendi/plugins/git/hooks/extractCrossRef.php --repo_path="$repo_location" --login="$tuleap_login" --type="git_commit" --rev_id="$tuleap_repo_name/$rev"
	done
}

# --- Config
# Set GIT_DIR either from the working directory, or from the environment
# variable.
GIT_DIR=$(git rev-parse --git-dir 2>/dev/null)
if [ -z "$GIT_DIR" ]; then
	echo >&2 "fatal: post-receive-reference: GIT_DIR not set"
	exit 1
fi

if [ -n $oldrev -a -n $newrev ]; then
	extractRef $newrev $oldrev
else
	echo >&2 "fatal: post-receive-reference: Usage is post-receive-reference oldrev newrev"
	exit 1
fi
