#!/bin/sh
#
# An example hook script for the post-receive event
#
# This script is run after receive-pack has accepted a pack and the
# repository has been updated.  It is passed arguments in through stdin
# in the form
#  <oldrev> <newrev> <refname>
# For example:
#  aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master
#
# see contrib/hooks/ for an sample, or uncomment the next line (on debian)
#

#. /usr/share/codendi/plugins/git/hooks/post-receive-email 2>/dev/null

push_timestamp=$(date +%s)

git_dir_path=$(git rev-parse --git-dir 2>/dev/null)
repository_path=$(cd $git_dir_path; pwd)

if [ ! -z "$GL_USER" ]; then
    user_name="$GL_USER"
else
    user_name=$(whoami)
fi

while read oldrev newrev refname
    do
	echo $oldrev $newrev $refname | /usr/share/codendi/plugins/git/hooks/post-receive-email 2>/dev/null
        /usr/lib/codendi/bin/git-post-receive.pl $repository_path $user_name $oldrev $newrev $refname
	. /usr/share/codendi/plugins/git/hooks/post-receive-log 2>/dev/null
	. /usr/share/codendi/plugins/git/hooks/post-receive-trigger-ci 2>/dev/null
	#/usr/share/codendi/plugins/git/hooks/post-receive.php "$repository_path" "$user_name" "$oldrev" "$newrev" "$refname"
    done

