#!/bin/sh

logGitPushes()
{
	# Tuleap specific: Git logging stuffs
	#@TODO : Non fast-forward pushes ???

	revtype=$(git cat-file -t "$newrev")
	tuleap_login=$(whoami)
	repo_location=$(cd $GIT_DIR; pwd)
	tuleap_repo_name=$(basename $repo_location | sed -e 's/\.git$//')
	tuleap_group_name=$(basename $(dirname $repo_location))

	nbcommits=0
	 if expr "$oldrev" : '0*$' >/dev/null 
		then
		revspec=$newrev
		else
		revspec=$oldrev..$newrev
	fi

	for rev in $(git rev-list $revspec)
	do
		nbcommits=$((nbcommits+1))
	done

	php /usr/share/codendi/plugins/git/hooks/gitLog.php --group_name="$tuleap_group_name" --login="$tuleap_login" --type="$revtype" --repo_name="$tuleap_repo_name" --commits_number="$nbcommits" > /dev/null

}

# --- Config
# Set GIT_DIR either from the working directory, or from the environment
# variable.
GIT_DIR=$(git rev-parse --git-dir 2>/dev/null)
if [ -z "$GIT_DIR" ]; then
	echo >&2 "fatal: post-receive: GIT_DIR not set"
	exit 1
fi
logGitPushes $2 $1
