#!/bin/sh
#
# An example hook script for the post-receive event
#
# This script is run after receive-pack has accepted a pack and the
# repository has been updated.  It is passed arguments in through stdin
# in the form
#  <oldrev> <newrev> <refname>
# For example:
#  aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master
#
# see contrib/hooks/ for an sample, or uncomment the next line (on debian)
#

. /usr/share/codendi/plugins/git/hooks/post-receive-email 2>/dev/null

## Tested with real size repository (dalvik from Android source)
## On my 2CPU 4GB RAM server, load raised up to 60 and I had to
## force power off of the machine

#while read oldrev newrev refname
#    do
#       echo `date` $oldrev $newrev $refname >> /tmp/push.log
#       echo $oldrev $newrev $refname | /usr/share/codendi/plugins/git/hooks/post-receive-email >&- 2>&- &
#       . /usr/share/codendi/plugins/git/hooks/post-receive-log $oldrev $newrev >&- 2>&- &
#    done
