#!/bin/sh
# Copyright (c) Enalean, 2023 - Present. All Rights Reserved.
#
# This file is a part of Tuleap.
#
# Tuleap is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Tuleap is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Tuleap. If not, see <http://www.gnu.org/licenses/>.

set -euo pipefail

git_dir_path=$(/usr/lib/tuleap/git/bin/git rev-parse --git-dir 2>/dev/null)
repository_path=$(cd "$git_dir_path"; pwd)

if [[ "${GIT_QUARANTINE_PATH:-}" =~ "$repository_path"* ]]; then
    # Allow read access to the gitolite group
    chmod g+rx "$GIT_QUARANTINE_PATH"
fi

sudo -u codendiadm /usr/bin/tuleap git:pre-receive -- "$repository_path"
