<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload9e74ce843c3fd8d984f7356124892644($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'referencealias_mediawikiplugin' => '/referencealias_mediawikiPlugin.class.php',
            'tuleap\\referencealiasmediawiki\\compatibilitydao' => '/CompatibilityDao.php',
            'tuleap\\referencealiasmediawiki\\plugin\\plugindescriptor' => '/ReferenceAliasMediawiki/Plugin/PluginDescriptor.php',
            'tuleap\\referencealiasmediawiki\\plugin\\plugininfo' => '/ReferenceAliasMediawiki/Plugin/PluginInfo.php',
            'tuleap\\referencealiasmediawiki\\referencesbuilder' => '/ReferencesBuilder.php',
            'tuleap\\referencealiasmediawiki\\referencesimporter' => '/ReferencesImporter.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload9e74ce843c3fd8d984f7356124892644');
// @codeCoverageIgnoreEnd
