<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoloadc0e370cf52320b8dcb8259b91fad3354($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'browserplugin' => '/BrowserPlugin.class.php',
            'datetime' => '/ResolvPHP-5.1.6-Compatibility.php',
            'datetimezone' => '/ResolvPHP-5.1.6-Compatibility.php',
            'webdav_docmancontroller' => '/FS/WebDAV_DocmanController.class.php',
            'webdav_request' => '/WebDAV_Request.class.php',
            'webdav_response' => '/WebDAV_Response.class.php',
            'webdav_urlverification' => '/Webdav_URLVerification.class.php',
            'webdavauthentication' => '/WebDAVAuthentication.class.php',
            'webdavdocmandocument' => '/FS/WebDAVDocmanDocument.class.php',
            'webdavdocmanfile' => '/FS/WebDAVDocmanFile.class.php',
            'webdavdocmanfolder' => '/FS/WebDAVDocmanFolder.class.php',
            'webdavexceptionservererror' => '/exception/WebDAVExceptionServerError.class.php',
            'webdavfrs' => '/FS/WebDAVFRS.class.php',
            'webdavfrsfile' => '/FS/WebDAVFRSFile.class.php',
            'webdavfrspackage' => '/FS/WebDAVFRSPackage.class.php',
            'webdavfrsrelease' => '/FS/WebDAVFRSRelease.class.php',
            'webdavplugin' => '/webdavPlugin.class.php',
            'webdavplugindescriptor' => '/WebDAVPluginDescriptor.class.php',
            'webdavplugininfo' => '/WebDAVPluginInfo.class.php',
            'webdavproject' => '/FS/WebDAVProject.class.php',
            'webdavroot' => '/FS/WebDAVRoot.class.php',
            'webdavtree' => '/WebDAVTree.class.php',
            'webdavutils' => '/WebDAVUtils.class.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoloadc0e370cf52320b8dcb8259b91fad3354');
// @codeCoverageIgnoreEnd