<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload4e739e4248e79fcc3eeb4cb017dff26f($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'botmattermost_agiledashboardplugin' => '/botmattermost_agiledashboardPlugin.class.php',
            'tuleap\\botmattermostagiledashboard\\botagiledashboard\\botagiledashboard' => '/BotMattermostAgileDashboard/BotAgileDashboard/BotAgileDashboard.php',
            'tuleap\\botmattermostagiledashboard\\botagiledashboard\\botagiledashboarddao' => '/BotMattermostAgileDashboard/BotAgileDashboard/BotAgileDashboardDao.php',
            'tuleap\\botmattermostagiledashboard\\botagiledashboard\\botagiledashboardfactory' => '/BotMattermostAgileDashboard/BotAgileDashboard/BotAgileDashboardFactory.php',
            'tuleap\\botmattermostagiledashboard\\controller' => '/BotMattermostAgileDashboard/Controller.php',
            'tuleap\\botmattermostagiledashboard\\plugin\\plugindescriptor' => '/BotMattermostAgileDashboard/Plugin/PluginDescriptor.php',
            'tuleap\\botmattermostagiledashboard\\plugin\\plugininfo' => '/BotMattermostAgileDashboard/Plugin/PluginInfo.php',
            'tuleap\\botmattermostagiledashboard\\presenter\\adminnotificationpresenter' => '/BotMattermostAgileDashboard/Presenter/AdminNotificationPresenter.php',
            'tuleap\\botmattermostagiledashboard\\presenter\\standupsummarypresenter' => '/BotMattermostAgileDashboard/Presenter/StandUpSummaryPresenter.php',
            'tuleap\\botmattermostagiledashboard\\senderservices\\standupnotificationbuilder' => '/BotMattermostAgileDashboard/SenderServices/StandUpNotificationBuilder.php',
            'tuleap\\botmattermostagiledashboard\\senderservices\\standupnotificationsender' => '/BotMattermostAgileDashboard/SenderServices/StandUpNotificationSender.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload4e739e4248e79fcc3eeb4cb017dff26f');
// @codeCoverageIgnoreEnd
