<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload2f37625d0681a2f7a9a71857a8ad34a6($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'botmattermost_gitplugin' => '/botmattermost_gitPlugin.class.php',
            'tuleap\\botmattermostgit\\botmattermostgitnotification\\botmattermostgitnotification' => '/BotMattermostGit/BotMattermostGitNotification/BotMattermostGitNotification.php',
            'tuleap\\botmattermostgit\\botmattermostgitnotification\\dao' => '/BotMattermostGit/BotMattermostGitNotification/Dao.php',
            'tuleap\\botmattermostgit\\botmattermostgitnotification\\factory' => '/BotMattermostGit/BotMattermostGitNotification/Factory.php',
            'tuleap\\botmattermostgit\\botmattermostgitnotification\\validator' => '/BotMattermostGit/BotMattermostGitNotification/Validator.php',
            'tuleap\\botmattermostgit\\controller' => '/BotMattermostGit/Controller.php',
            'tuleap\\botmattermostgit\\exception\\cannotcreatebotnotificationexception' => '/BotMattermostGit/Exception/CannotCreateBotNotificationException.php',
            'tuleap\\botmattermostgit\\exception\\cannotdeletebotnotificationexception' => '/BotMattermostGit/Exception/CannotDeleteBotNotificationException.php',
            'tuleap\\botmattermostgit\\exception\\cannotupdatebotnotificationexception' => '/BotMattermostGit/Exception/CannotUpdateBotNotificationException.php',
            'tuleap\\botmattermostgit\\plugin\\plugindescriptor' => '/BotMattermostGit/Plugin/PluginDescriptor.php',
            'tuleap\\botmattermostgit\\plugin\\plugininfo' => '/BotMattermostGit/Plugin/PluginInfo.php',
            'tuleap\\botmattermostgit\\presenter' => '/BotMattermostGit/Presenter/Presenter.php',
            'tuleap\\botmattermostgit\\senderservices\\attachmentpretextpresenter' => '/BotMattermostGit/Presenter/AttachmentPreTextPresenter.php',
            'tuleap\\botmattermostgit\\senderservices\\gitnotificationbuilder' => '/BotMattermostGit/SenderServices/GitNotificationBuilder.php',
            'tuleap\\botmattermostgit\\senderservices\\gitnotificationsender' => '/BotMattermostGit/SenderServices/GitNotificationSender.php',
            'tuleap\\botmattermostgit\\senderservices\\pullrequestnotificationbuilder' => '/BotMattermostGit/SenderServices/PullRequestNotificationBuilder.php',
            'tuleap\\botmattermostgit\\senderservices\\pullrequestnotificationsender' => '/BotMattermostGit/SenderServices/PullRequestNotificationSender.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload2f37625d0681a2f7a9a71857a8ad34a6');
// @codeCoverageIgnoreEnd
