<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload502063307f4b6570c9b1b354d5438ec3($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'pfo_plugin' => '/Plugin.php',
            'pfo_project' => '/Project.php',
            'pfo_user' => '/User.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload502063307f4b6570c9b1b354d5438ec3');
// @codeCoverageIgnoreEnd