<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoloadfc07f9c7ef6d053ca7528389207884a2($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'teamforge_compatplugin' => '/teamforge_compatPlugin.class.php',
            'teamforgecompat\\referencesimporter' => '/TeamforgeCompat/ReferencesImporter.class.php',
            'teamforgecompat\\teamforgecompatdao' => '/TeamforgeCompat/TeamforgeCompatDao.class.php',
            'teamforgecompat\\teamforgereferencesbuilder' => '/TeamforgeCompat/TeamforgeReferencesBuilder.class.php',
            'tuleap\\teamforgecompat\\plugin\\plugindescriptor' => '/TeamforgeCompat/Plugin/PluginDescriptor.php',
            'tuleap\\teamforgecompat\\plugin\\plugininfo' => '/TeamforgeCompat/Plugin/PluginInfo.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoloadfc07f9c7ef6d053ca7528389207884a2');
// @codeCoverageIgnoreEnd
