<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload62b075448b3ba48670ded87fd7e8e96c($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'archivedeleteditemsplugin' => '/archivedeleteditemsPlugin.class.php',
            'archivedeleteditemsplugindescriptor' => '/ArchiveDeletedItemsPluginDescriptor.class.php',
            'archivedeleteditemsplugininfo' => '/ArchiveDeletedItemsPluginInfo.class.php',
            'tuleap\\archivedeleteditems\\archivelogger' => '/ArchiveLogger.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload62b075448b3ba48670ded87fd7e8e96c');
// @codeCoverageIgnoreEnd
