<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload68460888ec90543b80a10f645730e4c7($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'soap_testdatabuilder' => '/TestDataBuilder.php',
            'soapbase' => '/SOAPBase.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload68460888ec90543b80a10f645730e4c7');
// @codeCoverageIgnoreEnd
