DROP TABLE IF EXISTS plugin_docmanwatermark_metadata_love_md_extension;
DROP TABLE IF EXISTS plugin_docmanwatermark_metadata_extension;
DROP TABLE IF EXISTS plugin_docmanwatermark_item_excluded;
DROP TABLE IF EXISTS plugin_docmanwatermark_item_excluded_log;
